# coding=utf-8
list = {
        'sign-parkingzoneend.fixed': 'sign-parkingzoneend',
        'mobilestage.trailer': 'Stage trailer',
        'log1.load': 'Log (47T)',
        'oshkosh_amplirol.truck': 'Oshkosh LVRS Amplirol',
        'GraveDiggerFTRWS.truck': 'Gravedigger w/Flextire + Aux RWS',
        'sennebogen5500jib3.truck': 'SENNEBOGEN 5500  35.5m boom 24.3m jib',
        'agorao.truck': 'Bus RVI Agora orange',
        'be428a3bdabde161a973cacf0b05f8db19db7348-peterbilt359.truck': 'Peterbilt 359',
        'scaniaak.truck': 'Bus Zania',
        'FLK-1500-narrowtrack.truck': 'AinTech FLK-1500 NT 58m',
        'sethlift.load': 'sethlift',
        'bbkenwortht800_31.truck': 'Kenworth T800 Daycab 2 axle shorter frame',
        'JeepOffRoad.truck': 'Jeep Cherokee Froggy',
        'arway.truck': 'Irisbus Arway (v2)',
        '0008UID_pallet250.load': 'EUR-pallet loaded 250kg',
        'Backdraft.truck': 'Backdraft',
        'bbkenwortht800_24.truck': 'Kenworth T800W sleeper toolbox tri-axle longframe',
        '6153UID_blade.load': 'Mitsubishi MWT92 Wind Engine Rotor with Carrier',
        'iep-federalpolice.truck': 'Federal Police (Chally)',
        'squishycrushcarsrg.load': '3 Crushable Cars (red and green)',
        'VW_T3_2WD_Race.truck': 'VW T3 2WD Racing',
        'HalfPint.truck': '1/2 Pint',
        'a1da0UID-crane.fixed': 'Fixed Crane',
        '143boxtrailer.trailer': '143 reefer Sties',
        'StormDamage.truck': 'Storm Damage',
        'FLK-1500-longboom-power.truck': 'AinTech FLK-1500 108m P-boom',
        'sign-nocars.fixed': 'sign-nocars',
        'BruteForce.truck': 'Brute Force',
        'Box69CamaroRed.truck': 'Box 1969 Camaro RedDragon',
        'DonkeyKong.truck': 'Donkey Kong',
        'afe677a27542bf4c049fe00a24d001f36074f6da-Renault_kerax_Ladder.truck': 'Kerax Firetruck Ladder 1',
        'backwardsbob.truck': 'Backwards Bob',
        'Wrangler1.truck': 'Jeep Wrangler JK | KEYBOARD',
        '852330c5fa103d1e3f281a346dfc5da59e653fbf-beercrate.load': 'Crate of beer',
        'xas66.load': 'XAS 66 compressor',
        '184cUID-panther8x8hret.truck': 'Rosenbauer Panther 8x8 HRET',
        '1fffUID-AT-TE.truck': 'AT-TE',
        'gavrilomegalow.truck': 'Gavril Omega Twelve',
        'c5b5UID-ScaniaR480TL.truck': 'Scania R480 Topline 4x2',
        'Pickupdacia.truck': 'Dacia pick-up',
        'a234UID-ScaniaR560sidepipe.truck': 'Scania R Topline 6x2 sidepipe',
        'elmatador.truck': 'El Matador',
        'burnsidecoupe.truck': 'Burnside Coupe',
        'tmnt.truck': 'Teenage Mutant Ninja Turtles',
        '59aeUID-boxtruck.truck': 'Small boxtruck',
        'PeelP50Blue.truck': 'Peel P50 Blue',
        'badhabit.truck': 'Bad Habit',
        'SpecDAF_XF105_8x4.truck': 'DAF Firetruck Special Load PL',
        'KME_Cat.truck': 'KME Predator - Caterpillar',
        'JeepWranglerUnlimited-(Stock).truck': 'Jeep Wrangler Unlimited-(Stock)',
        'JeepBartoPLwhite.truck': 'Jeep Cherokee white',
        'bbkenwortht800_28.truck': 'Kenworth T800 Long frame Logtruck',
        'sign-maxspeed120.fixed': 'sign-maxspeed120',
        'Bigfootfirestone.truck': 'Firestone Bigfoot',
        'b436UID_dhg700c.truck': 'Henschel DHG 700 C',
        'sign-bluearrowup.fixed': 'sign-bluearrowup',
        'iep-citypolice.truck': 'City Police (Chally)',
        'ple003_zil135_nyerges.truck': 'ZIL-135 with fifth wheel',
        'F350.truck': 'F-350 Crew Cab 4x4',
        'bbkenwortht800_12.truck': 'Kenworth T800 4th axle Extended Flatbed',
        '6a8cUID_demag_storage.load': 'DEMAG ZKKE Storage',
        '08a1UID-jerseybarrier.load': 'jersey barrier',
        'MarsLC.airplane': 'MarsLC',
        'PLarielladder.truck': 'MAN Firetruck Elevator PL',
        'Autocar.truck': 'Autocar',
        'MichiganIceMonster.truck': 'Michigan Ice Monster',
        'spidertrax5.truck': 'Spidertrax Crawler | GreenComp',
        'b6b0UID-semi.truck': 'Daf Semi truck',
        'YotaFlatbed1.truck': '1980 Toyota Flatbed 4x4 (flex-tires)',
        '22af34f948dc237478c8f88de3484dc84d83abe1arielladder.truck': 'MAN Firetruck Elevator',
        '3c32f3a35ff28a33ef3c35b8c0c9441494b88f5c-mercedesCitaro.truck': 'Mercedes-Benz Citaro L',
        'sign-bump.fixed': 'sign-bump',
        '80ton.load': '80ton ballast',
        'gavrilrally.truck': 'Gavril G2X',
        'bbkenwortht800_17.truck': 'Kenworth T800 tilt Flatbed long frame 4-axle',
        'GraveDigger.truck': 'Gravedigger',
        'gavrilzeta2wd.truck': 'Gavril Zeta 2WD',
        'sign-rightpriority.fixed': 'sign-rightpriority',
        'Duece.truck': 'Duece',
        '6810cUID-chevs10low.truck': 'Chevrolet S10 Slammed',
        'FLK-1500-narrowtrack-longboom-power.truck': 'AinTech FLK-1500 NT 108m P-boom',
        'MechanicalMischief.truck': 'Mechanical Mischief',
        'devastator.truck': 'Devastator',
        'MonsterMutt2.truck': 'Monster Mutt (Tarlton)',
        'prowler.truck': 'Prowler',
        'nooteboom_teletrailer_yellow.trailer': 'Nooteboom Teletrailer (yellow)',
        'be428a3bdabde161a973cacf0b05f8db19db7348-peterbilt359-long.truck': 'Peterbilt 359 Daycab with long frame',
        'sign-novehicles.fixed': 'sign-novehicles',
        'bbkenwortht800_27.truck': 'Kenworth T800 sleeper short frame heavy haul',
        'sign-descent10.fixed': 'sign-descent10',
        'arway1.truck': '2002 Thomas Saf-T-Liner HDX',
        'ce_2.load': 'cargo engine 2',
        'Kenworthlogtrailer.trailer': 'Kenworth Log Trailer',
        '93edUID-K100semiFlat.truck': 'Kenworth K100 Semi FlatTop',
        '4x4_Jeep_Cherokee_BigFoot.truck': 'Jeep Cherokee BigFoot',
        'b31cUID-wahoo.boat': 'Wahoo boat',
        '49fordfordor.truck': '1949 Ford Fordor',
        'Dodge_Ram892.truck': 'Dodge Ram 5500 Vulcan 892',
        '100ton.load': '100ton ballast',
        '184cUID-panther8x8.truck': 'Rosenbauer Panther 8x8',
        'GravediggerXX.truck': 'Grave Digger XX',
        'GDLegend.truck': 'Grave Digger The Legend',
        'Audi80_16fwd.truck': 'Audi 80 1.6 FWD',
        'windblade.load': 'wind turbine blade (7T)',
        'BoxDodgeRamCollision.truck': 'Box Dodge Cummins Collision',
        'Spike.truck': 'Spike',
        'sign-bluearrowdown.fixed': 'sign-bluearrowdown',
        'dodge2.truck': 'Dodge Pickup 2',
        '4161UID-houseboat.boat': 'Houseboat',
        'sign-maxspeed50.fixed': 'sign-maxspeed50',
        '6gq3y835-policejeep.truck': 'Jeep Cherokee Police',
        'Merc_O305.truck': 'Mercedes-Benz O305',
        'Obsessed.truck': 'Obsessed',
        'Tatra-T813-Dakar.truck': 'Tatra-T813 8x8 DAKAR',
        '3344UID-concretebeam60ton.load': 'Concrete beam 28.5m',
        'arwaymh.truck': 'Irisbus Arway Motorhome (v1)',
        'sign-fall.fixed': 'sign-fall',
        'agoralo.truck': 'Bus RVI Agora london',
        'JeepMichiganPolice.truck': 'Jeep Cherokee Michigan Police',
        'sign-maxspeed110.fixed': 'sign-maxspeed110',
        'GravediggerXVI.truck': 'Grave Digger XVI',
        'a1da0UID-monorail.truck': 'Monorail',
        'MMCP-DM.truck': 'Mitsubishi Pajero MT',
        '6squishycrushcars.load': '6 Crushable Cars (blue and white)',
        'jeepconstruction.truck': 'Jeep Cherokee Construction',
        'Bigfootblackblue.truck': 'Black and Blue Bigfoot',
        'tntcr4te.load': 'TNT Crate',
        'JeepBartoPLgold.truck': 'Jeep Cherokee Gold',
        'trafficcontrol.trailer': 'Traffic Control Trailer',
        'sign-bluearrow2downleft.fixed': 'sign-bluearrow2downleft',
        'Box5W900.truck': 'Box5 W900 Sleeper',
        '2c97UID-counterweight-h.load': 'Manitou Counterweight - Heavy',
        '4x4_Jeep_Cherokee.truck': 'Jeep Cherokee',
        '350z.truck': 'Nissan 350Z Coupe orange',
        'S10slammed.truck': 'Chevrolet S10 Slammed',
        '1584e13c9b2a4d7e02266390107e2d00d572de29-cementtruck.truck': 'Cement Truck',
        'sign-blueYleft.fixed': 'sign-blueYleft',
        'sign-crosswinds.fixed': 'sign-crosswinds',
        'mammoet-100t.load': 'Load (100tons)',
        'Larvkran-Superlift-CW-Trailer-180t.load': 'FLK-1500 superlift-trailer ballast (180t)',
        'Lowboy.trailer': 'Lowboy',
        'iep-statepolice.truck': 'State Police (Chally)',
        'PM-580.truck': 'PM-580',
        'simba_8x8_RORsk.truck': 'Simba 8x8 RORport',
        '94Dodge.truck': '94Dodge',
        'PR180rtm.truck': 'Renault PR180 RTM',
        '877cUID-dakar2007_renault_kerax.truck': 'Dakar 2007 Renault Kerax',
        'b70faUID-Farmwindtop.trailer': 'Farm Windmill',
        'Ford_F350_bumperpull.truck': 'Ford SD 4x4 Bumper pull',
        '726fUID-Gremlin.truck': 'AMC Gremlin',
        'MTVRcabchassis.truck': 'MTVR Cab Chassis',
        'Bountyhunter2.truck': 'Bounty Hunter (Winslow)',
        'hovertestv3.truck': 'Hovertest-3-0',
        'Bova.truck': 'Bova Futura FH12',
        'ITDdaf-truck.truck': 'DAF ITD',
        'gx187.truck': 'Heuliez GX 187 CTRL',
        'squishycj.truck': 'Jeep CJ Custom Crawler',
        '7517UID-bobcats130balespoon.truck': 'Bobcat S130 with Hay Bale Spoon',
        '140ton.load': '140ton ballast',
        '2c97UID-ManitouT.truck': 'Manitou MLT 731 with Truss Boom',
        'nitrocircus.truck': 'Nitro Circus',
        'Box5DeuceTractor.truck': 'Deuce and a Half Tractor 5th Wheel - Box5',
        'Winch_point.load': 'Winch point_1',
        'a8aea20c89d9fad8030276b3816f1d37245b1c05-volvo_fl6_hatch.truck': 'Volvo FL6 Firetruck IGS',
        'BBD-LTM-1095-extra-axle.truck': 'Liebherr LTM 1095-5.1 with extra axle',
        'sign-maxspeed80.fixed': 'sign-maxspeed80',
        '93edUID-K100semiChrome.truck': 'Kenworth K100 Semi Show',
        'BigfootE3.truck': 'Bigfoot 15 E3',
        'Ironwarrior.truck': 'Iron Warrior',
        '4x4mercflatbed2.truck': '4X4 merc 1317 Flatbed withpaint',
        'Allis_Chalmers_HD11.truck': 'Allis-Chalmers HD11',
        'ebe2UID-LegocarX.truck': 'Lego car (Manual transfer case)',
        'bbkenwortht800_30.truck': 'Kenworth T800W two-axle Daycab longframe',
        'AirborneRanger.truck': 'Airborne Ranger',
        'mammoet-20t.load': 'Load (20tons)',
        'GravediggerXIV.truck': 'Grave Digger XIV',
        'rammunition.truck': 'Rammunition',
        'AC500-2 60mluffing JIB.truck': 'Terex-Demag AC500- 60m luffing jib',
        'bbkenwortht800_9.truck': 'Kenworth T800 terrain editor',
        'sign-Scurveright.fixed': 'sign-Scurveright',
        'medicbloc.load': 'medicbloc',
        'SIIILW04.truck': 'Land Rover SIII Lightweight Green',
        'MAN_F2000_box_4X4.truck': 'MAN F2000 Evo Dry Van 4x4 (19.414)',
        'mod_platform_driveable.load': 'modulare platform middle drive able',
        '2c97UID-Bucket.load': 'Manitou Bucket',
        'nooteboom_teletrailer_blue.trailer': 'Nooteboom Teletrailer (blue)',
        'bbkenwortht800_37.truck': 'Kenworth T800 Tilt Flatbed regular frame',
        'Desert_Trails-SoundLoad2.load': 'SoundLoad',
        'Captainscurse.truck': 'Captain\'s Curse',
        '852330c5fa103d1e3f281a346dfc5da59e653fbf-renault-pmr.truck': 'Renault Express Pimped',
        'OutbackThunda.truck': 'Outback Thunda',
        'gavrilbandit300.truck': 'Gavril Bandit 300',
        'ZDMdaf.truck': 'DAF Federal Police CP-OPS',
        '1ab4UID-MTVRdumpbed.truck': 'MTVR Dumpbed',
        '78ea1UID-liebherr.truck': 'Liebherr',
        '6a8cUID_1_door.fixed': 'Hall Doors',
        'rail1tgerbuf.fixed': 'German Train Buffer',
        '6a8cUID_door.fixed': 'Hall Doors',
        'ece03UIDtug-atlas.boat': 'Atlas class tug',
        'Flak.load': 'Ampliroll Contanier',
        'YotaLongBed.truck': '1980 Toyota Longbed 4x4',
        'Grinder.truck': 'Grinder (Soza)',
        'BoxDodgeRamTruggyFT.truck': 'Box Dodge Cummins Truggy (FlexTire)',
        'gavrilzetacrawler.truck': 'Gavril Zeta Crawler',
        'sign-bluearrowleft.fixed': 'sign-bluearrowleft',
        'b6b0UID-semi.trailer': 'Semi trailer (37tons)',
        '6153UID_tower1.load': 'Mitsubishi MWT92 Wind Engine Tower 1',
        'Horten-229-LS.truck': 'Horten-229-LS',
        'XXX.truck': 'XXX',
        'mohawk.truck': 'Mohawk Warrior',
        'DestructibleBarricade2P.load': 'Destructible Barricade 2P',
        'nooteboom_teletrailer.trailer': 'Nooteboom Teletrailer',
        'a09eUID-travego0.7f.truck': 'Merceds Travego Feuerwehr',
        'Bountyhunter.truck': 'Bounty Hunter (Creten)',
        'ad2dUID-smit.boat': 'Smit Rotterdam Tug',
        'bbkenwortht800_2.truck': 'Kenworth T800 6x6 Daycab regular frame',
        '852330c5fa103d1e3f281a346dfc5da59e653fbf-toolbox.load': 'Toolbox',
        'rail1tPnt150r10dR.fixed': 'Railroad Switch r',
        'gavrilmv4r.truck': 'Gavril MV4R',
        'sign-maxspeed100.fixed': 'sign-maxspeed100',
        'JeepBartoPL5.truck': 'Jeep Cherokee Generic Police',
        'Reptoid.truck': 'Reptoid',
        'S53R_V2.truck': 'Renault S53R Version 2',
        'BulldozerWilman.truck': 'Bulldozer (Werner)',
        'bcdeabcf82f5aab4e3a964a47565c5a66f057be2-travegotrailer.trailer': 'Travego trailer',
        'BoxSamurai.truck': 'Box5 Suzuki Samurai Wheeler',
        'Thrasher.truck': 'Thrasher',
        'Autocar_dumper.truck': 'Autocar dump truck',
        'BoxUnimog.truck': 'Unimog 406',
        'IC CE-300.truck': 'CE300',
        'HotWheels.truck': 'Hot Wheels',
        'spidertrax2.truck': 'Spidertrax Crawler | CompBlue',
        'Audi80_16rwd.truck': 'Audi 80 1.6 RWD',
        'haybale.load': 'Hay Bale',
        '350z11.truck': 'Nissan 350Z Coupe orange Convertible',
        'Madusa.truck': 'Madusa',
        'agorar.truck': 'Bus RVI Agora red',
        'Larvkran-Superlift-CW-Trailer-300t.load': 'FLK-1500 superlift-trailer ballast (300t)',
        'iep-firecar.truck': 'Fire Chief (Chally)',
        'EscaladeMonsterFTRWS.truck': 'Escalade Monster Truck w/Flextire + Aux RWS',
        'FlxibleMetroD.truck': 'Flxible Metro D',
        'traspaleta.truck': 'traspaleta',
        'sennebogen55003.truck': 'SENNEBOGEN 5500  57.9m boom',
        '57611UIDfiretruck-si.truck': 'Starling Island Firetruck MB LF 16',
        '888cbc11dd129c74eeb31cc5c035b5a474579573-reefer.trailer': 'Reefer Spread Axle',
        'bbkenwortht800_22.truck': 'Kenworth T800 sleeper short frame',
        'Audi80_18rwd.truck': 'Audi 80 1.8 RWD',
        'sign-trafficlight.fixed': 'sign-trafficlight',
        'MM-Race-400-LS.truck': 'MeanMachine-Race-400-LS',
        'sprinterPogotowie.truck': 'Mercedes Sprinter Ambulance',
        'sign-parking.fixed': 'sign-parking',
        'ple003_zil135uragan_bc.truck': 'ZIL-135 bare chassis',
        '5822UID-an-12.airplane': 'Antonov 12',
        'bbkenwortht800_11.truck': 'Kenworth T800 daycab short frame Tbox',
        'burnsideconvertible.truck': 'Burnside Convertible',
        'Mercedes-BenzO405.truck': 'Mercedes-BenzO405N',
        'MH_RW2.truck': 'Feuerwehr Marktheim RW 2',
        'ilan.boat': 'Ilan',
        'Gooseneck.load': 'Gooseneck',
        'mammoet-500t.load': 'Load (500tons)',
        'bbkenwortht800_4.truck': 'Kenworth T800 6x6 Logtruck',
        'agorab.truck': 'Bus RVI Agora black',
        'S10offroad.truck': 'Chevrolet S10 Off-Road',
        'd9dozer.truck': 'Caterpillar D9H TrackDozer',
        'PeelP50Red.truck': 'Peel P50 Red',
        'boobytrap.load': 'boobytrap',
        'SIIILW05.truck': 'Land Rover SIII Lightweight Red',
        '07366UID-C1-tunnel-WIP.boat': 'C1 Offshore WIP working rudder F7 F8',
        'Bigfoot1635th.truck': 'Bigfoot 16 35th Anniversary (RetroFoot)',
        'gavrilmv4s.truck': 'Gavril MV4S',
        'aa21bUID-towbar.load': 'AST-1X Towbar',
        'crusader.truck': 'Lucas Oil Crusader',
        '2128UID-crate-light.load': 'Crate (500kg)',
        '7dcaUID-CXT.truck': 'International CXT 3212',
        'z359UID-dodgepolice.truck': 'Dodge Police Car',
        'sign-slippery.fixed': 'sign-slippery',
        '0c0ecee99fd6c10a827a4a3d2c5f032b72e01470-trailer.trailer': 'Trailer with Hatch',
        'MarsRC.airplane': 'MarsRC',
        'sign-nouturn.fixed': 'sign-nouturn',
        '40ftcontainer.load': '40ft container',
        'squishyblacksmith.truck': 'Squishy Black Smith w/Flextire',
        'gavrilzetaswb.truck': 'Gavril Zeta SWB',
        'spidertrax4.truck': 'Spidertrax Crawler | MidnightChrome',
        'bbkenwortht800_6.truck': 'Kenworth T800 tri axle boxtruck',
        'ElToroLocoPEI.truck': 'El Toro Loco (McDonough)',
        'heatexchanger.load': 'Heatexchanger (50tons)',
        'a09eUID-travegotrailer.trailer': 'Travego trailer',
        '48ftcontainer.load': '48ft container',
        'Landrover1tonne.truck': 'Land Rover 1 tonne',
        'roadtrain-trailer-3.trailer': 'Road Train Trailer (set of 3)',
        'gunslinger.truck': 'Gunslinger',
        '6219f3c1118d3cffc9dcf7f43aa8bee4481df01edafwrecker.truck': 'DAF Firetruck Wrecker',
        'sign-Scurveleft.fixed': 'sign-Scurveleft',
        '20ftcontainer.load': '20ft container',
        'tirestack02a.load': 'Tire Stack Orange X4',
        'be428a3bdabde161a973cacf0b05f8db19db7348-p359_8x6.truck': 'Peterbilt 359 8x6',
        'b77390b72b40492e54617d10caf831781abbd745-astro.truck': 'Chevrolet Astro LT',
        '49fordindiana.truck': '1949 Ford US Army',
        'MM-Baja-250-LS.truck': 'MeanMachine-Baja-250-LS',
        'VW_T3_2WD.truck': 'VW T3 2WD',
        'b6b0UID-semiflat.trailer': 'Flatbed semi trailer',
        '7a6eUID-mantgx26540semicrane.truck': 'MAN TGX 26.540 Semi with crane',
        'sign-crossing.fixed': 'sign-crossing',
        'squishybrutus.truck': 'Squishy Brutus w/Flextire',
        'b77390b72b40492e54617d10caf831781abbd745-astro2.truck': '\'05 GMC Safari Grand Canyon Edition AWD',
        'squishycrushcarvan.load': 'Crushable stack (car > van > car)',
        'dad5UID-ss.truck': 'Jeep Cherokee rally 1',
        'ebe2UID-Lego_police.truck': 'Lego Police car',
        '95bbUID-agoral.truck': 'Bus RVI Agora L',
        'bbkenwortht800_26.truck': 'Kenworth T800 sleeper Flatbed short frame',
        'GOPR-CPOPS_renault_kerax.truck': 'Kerax Firetruck CP-OPS',
        '182bUID-MML2011.truck': 'Mitsubishi L200 DI-D',
        'westernrenegade.truck': 'Western Renegade',
        'BackdraftW.truck': 'Backdraft (White)',
        '0b86UID-ArrowBoardTrailer.trailer': 'Arrow Board Trailer',
        'log3.load': 'Log (11T)',
        'Desert_Trails-SoundLoad2.fixed': 'SoundLoad',
        'GravediggerXVIII.truck': 'Grave Digger XVIII',
        'bbkenwortht800_39.truck': 'Kenworth T800W Daycab heavy haul 4-axle heavyframe',
        'VirginiaGiant.truck': 'Virginia Giant',
        'Stonecrusher1.truck': 'Stone Crusher (Sims)',
        '3dc2eUID-MM-Baja-250-LS.truck': 'MeanMachine-Baja-250-LS',
        'sennebogen5500jib5.truck': 'SENNEBOGEN 5500  35.5m boom 46.7m jib',
        'US_flatcar_grey.load': 'Flatcar 40ft grey',
        'S10drag.truck': 'Chevrolet S10 Drag',
        'twentyfootcontainer.load': 'Twenty-Foot Container (15tons)',
        'Jetmaster.airplane': 'Jetmaster-quad',
        'FirestoneBigfoot11.truck': 'Firestone Bigfoot 2011',
        'sign-unprotectedrrcrossingdistant.fixed': 'sign-unprotectedrrcrossingdistant',
        'spidertrax3.truck': 'Spidertrax Crawler | BlueFox',
        'dragonsbreath.truck': 'Dragon\'s Breath',
        'TLF-16-NG1222.truck': 'Mercedes Benz 1222 AF Neue Generation TLF 16/25',
        '3f3fUID-CoMaxOfficeS.truck': 'CoMax Office SingleCab w/Cargodoor',
        'burnsidewagon.truck': 'Burnside Wagon',
        'bobcats130.truck': 'Bobcat S130',
        '1312UID-mantgx18480.truck': 'MAN TGX 18.480 Semi',
        'kapellskar.boat': 'M/V Kapellskar',
        'Blue&White-ScaniaR470TL.truck': 'Scania R Topline 4x2 Blue & White',
        'ece03UIDbarge.boat': 'Barge (empty)',
        '6a8cUID_demag_hall.load': 'DEMAG ZKKE Hall',
        'MMHarrier.airplane': 'MarsMC',
        'sign-protectedrrcrossingdistant.fixed': 'sign-protectedrrcrossingdistant',
        'u5000racingne2wsusnedbed3.truck': 'Unimog U5000395racing4 new suspension',
        'afe677a27542bf4c049fe00a24d001f36074f6da-Renault_kerax_Ladder_2.truck': 'Kerax Firetruck Ladder 2',
        'iep-floridastatepolice.truck': 'Florida State Police (Chally)',
        'BBV95.truck': '1st Generation BlueBird Vision',
        'sqastro.truck': 'S&Q Chevy astro',
        'Newagg300TPG.truck': 'Van Hool New AGG 300 TPG',
        'a89a5UID-drawbridge.fixed': 'Edited truck',
        'bbkenwortht800_23.truck': 'Kenworth T800 sleeper short frame Tbox bed',
        'S53RX_V2.truck': 'Renault S53RX Version 2',
        'sign-autobahn.fixed': 'sign-autobahn',
        '2c97UID-counterweight-l.load': 'Manitou Counterweight - Light',
        'US_flatcar_red.load': 'Flatcar 40ft red',
        'burnsidewagonb.truck': 'Burnside BadWagon',
        'EscaladeMonster.truck': 'Escalade Monster Truck',
        'Unimog406.truck': 'Unimog 406',
        '767shocks.airplane': '767 AA Airliner',
        '45ftcontainer.load': '45ft container',
        'be8ffac24d8ce0c29ddb05b5781aa26e50c73119-TouringVolvo240.truck': 'Touring Volvo 240',
        'GraveDiggerMotorhome.load': 'GraveDigger Motorhome',
        'Box5Deuce.truck': 'Deuce and a Half - Box5',
        '607229df98a977d66fc67aa3d7ca2ce98a82975b-mercedesCitaro.truck': 'Mercedes-benz Citaro K',
        'sign-bluearrowright.fixed': 'sign-bluearrowright',
        'Box5DeuceBobbedV1.truck': 'Deuce and a Half Bobbed & Lifted - Box5',
        'ElToroLocoCRD.truck': 'El Toro Loco (McDonald)',
        'sign-twowaytraffic.fixed': 'sign-twowaytraffic',
        'Ford_F350_Super_Duty.truck': '2008 Ford SD F350 4x4',
        'bombinette.load': 'bombinette',
        'JeepBartoPL6.truck': 'Jeep Cherokee Generic Police 1',
        'superman.truck': 'Superman',
        'Box69CamaroBlack.truck': 'Box 1969 Camaro BlackKnight',
        'Flak_High.load': 'Ampliroll Contanier High',
        'Ironman.truck': 'Iron Man (O\'Donnel)',
        'Fullboar.truck': 'Fullboar',
        'WarWagon.truck': 'War Wagon',
        'captusafs.truck': 'Captain USA',
        'UnnamedUntamed.truck': 'Unnamed & Untamed',
        '635cUID-boxcar.load': 'Boxcar 40ft',
        'B2.airplane': 'B2 SPIRT',
        'c0963UID-Mig-25_12.airplane': 'Mig-25',
        'sign-crosswalk.fixed': 'sign-crosswalk',
        '3344UID-roofsegment.load': 'Roof segment load',
        'FLK-1500.truck': 'AinTech FLK-1500 58m',
        'Winch_point.truck': 'aWinch point_2AA',
        'BigHauler.load': 'BigHaul Bumperpull',
        '1312UID-mantgx33540semi.truck': 'MAN TGX 33.540 Semi',
        'KME_Detroit.truck': 'KME Predator - Detroit Diesel',
        'Avenger.truck': 'Avenger',
        'BoxDodgeRamEXTcollision.truck': 'Box Dodge Cummins Ext Collision',
        'VW_T3_4x4_RWsteer.truck': 'VW T3 SYNCRO with RW-steering',
        'WoodenCrate_HAZARD.load': 'Wooden Crate (HAZARD)',
        'PredatorPezo.truck': 'Pezo\'s Predator',
        'Sterlingfiretruck.truck': 'Sterling Bullet Firetruck',
        'sign-bluearrow2right.fixed': 'sign-bluearrow2right',
        'a90aUID-turbotwin.truck': '4x4 TurboTwin DAF v2',
        'opswitch.fixed': 'opswitch',
        'c69ffUID-ampliroll.truck': '4x4 DAF Ampliroll',
        'sign-roadnarrowsright.fixed': 'sign-roadnarrowsright',
        '3dc2eUID-MM-Race-400-LS.truck': 'MeanMachine-Race-400-LS',
        'marsdodgeS.truck': 'marsdodge-S',
        'BulldozerCRD.truck': 'Bulldozer (McDonald)',
        'inct.trailer': 'inclosed trailer',
        'Larvkran-Superlift-CW-480t.load': 'FLK-1500 superlift ballast (480t)',
        'FLK-1500-narrowtrack-longboom.truck': 'AinTech FLK-1500 NT 108m',
        'Unimog4064door.truck': 'Unimog 406 Four Door',
        '7e75UID-ALP-45DP_V2.truck': 'Bombardier ALP-45DP',
        '57611UIDsprinter-si-police.truck': 'Starling Island Police Sprinter',
        'd1ac11f8ca96956cd7fa5d20c0d9053c7b57fe58-Panther8x8.truck': 'Rosenbauer Panther 8x8',
        'MH_LF1612.truck': 'Feuerwehr Marktheim LF 16/12',
        'Rhinoracer.truck': 'Yamaha Rhino (Race)',
        '69d1f86083cd690d6277d44db1065e527ec0639f-ampliroll.truck': 'DAF 4X4 Firetruck ampliroll',
        'rail1tPnt190r10dL.fixed': 'Railroad Switch l',
        'dccb971c34d932f338f0b325d6ddaef97af36961-ampliroll.truck': 'Volvo FL12 8x8 Ampliroll',
        'BBD-LTM-1095-extra-axle-wrecker.truck': 'Liebherr LTM 1095-5.1 with extra wrecker axle',
        'mammoet-50t.load': 'Load (50tons)',
        'korppi-201012111600-ekeri.trailer': 'Ekeri semi trailer',
        '9c8776e651ae95447d34b736c826810bdcda903d-firetruck.truck': 'Volvo FL12 Firetruck',
        'MonsterMuttRottweiler.truck': 'Monster Mutt Rottweiler',
        'SterlingDodge.truck': '2009 Dodge Ram 2500 Heavy Duty',
        '6a8cUID_1_demag_northeast.load': 'DEMAG ZKKE northeast',
        '7e75UID-ALP-45DP_diesel.truck': 'Bombardier ALP-45DP (diesel mode)',
        'WoodenCrate_ARMY.load': 'Wooden Crate (ARMY)',
        '6153UID_tower2.load': 'Mitsubishi MWT92 Wind Engine Tower 2',
        'roadtrain-trailer-5.trailer': 'Road Train Trailers (set of 5)',
        'LJF-SoundLoad.fixed': 'SoundLoad',
        '3f3fUID-CoMaxOfficeD.truck': 'CoMax Office DoubleCab',
        'tirestack01a.load': 'Tire Stack Black X4',
        '27e3eUID-multibenne.truck': '4x4 DAF skiploader',
        'gavril_r.truck': 'Gavril G2R',
        'illuminator.truck': 'Illuminator',
        '140b3608241e354d594cca92c36af9ad00e746bc-mercedesCitaro.truck': 'Mercedes-Benz Citaro G',
        'Desert_Trails-SoundLoad.load': 'SoundLoad',
        '1DeRooyBus(With Flares).truck': 'DeRooy Bus',
        'ac500withoutssl.truck': 'Terex-Demag AC500- without ssl',
        'ba8ffUID-bajatruck-LS.truck': 'Dodge 1500 Baja LS',
        '0008UID_pallet1000.load': 'EUR-pallet loaded 1000kg',
        'd9crawler.truck': 'Caterpillar D9H TrackCrawler',
        'GraveDiggerRWS.truck': 'Gravedigger w/aux RWS',
        '1c81UID-P51.airplane': 'P51',
        'goldhofer_modul_4.trailer': 'Goldhofer THP/ET G+4+B+4 (manual steer)',
        'rockstar.truck': 'Rockstar',
        'sign-maxspeed30.fixed': 'sign-maxspeed30',
        'hummer_h1.truck': 'Hummer H1',
        'squishycrushcars.load': '3 Crushable Cars (blue and white)',
        'gavrilomegaDET.truck': 'Gavril Omega DET',
        '59aeUID-small_dump.truck': 'Small sweeper dumpbox version',
        'sennebogen5500jib1.truck': 'SENNEBOGEN 5500 24.3m boom 35.5mjib',
        'JeepAmbulance.truck': 'Jeep Cherokee Ambulance',
        'bbkenwortht800_21.truck': 'Kenworth T800 sleeper Extended Flatbed tri axle',
        'a-rocket.airplane': 'Skinned Rocket',
        'MH_TLF24.truck': 'Feuerwehr Marktheim TLF 24/50',
        '1312UID-mantgx41540semi.truck': 'MAN TGX 41.540 Semi',
        'JeepTrailer.trailer': 'Jeep Cherokee Trailer',
        '9d536f908e1c3ef0c40da46d4d26c0b5702caed1-billboard.trailer': 'Mobile Billboard Trailer.',
        'bde5d584936158c3f49a0ec282d17e63a327aee7-mercedesCitaro.truck': 'Mercedes-Benz Citaro',
        'odferry.boat': 'Open Deck Ferry',
        '49fordb.truck': '1949 Ford Moonshine Special',
        'b65cUID-gendryvan.trailer': 'Dry Van',
        'rofanzd4_diesel.truck': 'Rofan ZD4',
        'JeepBartoPL3.truck': 'Jeep Cherokee Wagoneer',
        'pr14sl2.truck': 'Renault PR 14 SL V2',
        '27e3eUID-multibennel.load': 'Multibenne container (10tons)',
        'a352aUID-K100semiChrome.truck': 'Kenworth K100 Semi Show',
        '4f5aUIDContainerChassis.trailer': 'Krone Box Liner',
        'sennebogen5500jib4.truck': 'SENNEBOGEN 5500  35.5m boom 35.5m jib',
        'Atego-CoMax.truck': 'Mercedes-Benz Atego 1318 w/CoMax-Box&Lift B',
        '8a232159f0ed28956d55ab555afe9398212ae671-larvband.truck': 'Tracked Thing',
        '7517UID-bobcats130.truck': 'Bobcat S130',
        'Titan.truck': 'Titan',
        'sign-deer.fixed': 'sign-deer',
        'PureAdrenaline.truck': 'Pure Adrenaline',
        'mercedes torino.truck': 'Mercedes Benz Torino G VI',
        '6ef84UID-1stgen.truck': '1st Gen Dodge Cummins 5th Wheel hitch',
        'submig.airplane': 'submig',
        'MaxD2.truck': 'Maximum Destruction (Elliott)',
        '2128UID-crate.load': 'Crate (3300kg)',
        'theemu1.truck': 'The Emu 1.0',
        'chevyswat.truck': 'Chevrolet SWAT Command',
        '4fb9UID-jerseybarrier.load': 'DNE Jersey Barrier',
        'BoxUnimogEXT.truck': 'Unimog 406 Passenger Carrier',
        'JeepWranglerUnlimited-(OFFROAD).truck': 'Jeep Wrangler Unlimited-(Offroad)',
        'telef.truck': 'telef',
        'gavrilbandit400GT.truck': 'Gavril Bandit 400 GT',
        'Box5W900W.truck': 'Box5 W900 Wrecker',
        'GravediggerXXIV.truck': 'Grave Digger XXIV',
        'PR180.truck': 'Renault PR180',
        'HH_DLK.truck': 'Fire Department Hamburg Ladder Truck',
        'ferrari-testarossaoff.truck': 'Ferrari Testarossa Offroad',
        'gavrilmv4.truck': 'Gavril MV4',
        'PL-firetruck.truck': 'Volvo FL12 Firetruck PL',
        '0008UID_pallet0.load': 'EUR-pallet empty',
        'nooteboom_teletrailer_red.trailer': 'Nooteboom Teletrailer (red)',
        'spacelift.truck': 'spacelift',
        'aramminicab.truck': 'aramminicab',
        'rail1tPnt190r634dRi.fixed': 'Railroad Switch 190r 6.34d ri',
        'Saft.trailer': 'Saft Trailer',
        'MaxD.truck': 'Maximum Destruction (Meents)',
        'ferryslipgate.fixed': 'Ferry Slip Gate',
        'Patriot.truck': 'The Patriot',
        'Box5W900F.truck': 'Box5 W900 Flatop Sleeper',
        'EltorolocoRSCRC.truck': 'El Toro Loco (Basl)',
        '24a159b6dc749abb4a38edbaef41f90d0229c2ee-lr1750.truck': 'Liebherr LR 1750 60/40 245t',
        'IronOutlaw2.truck': 'Iron Outlaw (Black)',
        '5822UID-an-12-cockpit.airplane': 'Antonov 12 (cockpit test version)',
        'a09eUID-volvo0.7.truck': 'Volvo 9900',
        '93edUID-K100semi.truck': 'Kenworth K100 Semi Workhorse',
        '3344UID-bridgegirder.load': 'Bridgegirder 37m',
        'Larvkran-Superlift-CW-140t.load': 'FLK-1500 superlift ballast (140t)',
        'Sisu-SA-150B.truck': 'Sisu SA-150 4x4 Masi',
        'WoodenCrate_THW.load': 'Wooden Crate (THW)',
        '0a77fUID_simsub01_v13.boat': 'DS9 Scientiffic Submarine',
        'GravediggerXXV.truck': 'Grave Digger XXV',
        '6153UID_hub_si.load': 'Mitsubishi MWT92 Wind Engine Rotor Hub',
        'elevador.fixed': 'elevador',
        '7517UID-haybale.load': 'Hay Bale',
        '2c97UID-ManitouW.truck': 'Manitou MLT 731 with winch',
        '6f52UID-daf.truck': '6x6 DAF Paris-Dakar',
        'oildrumsstacked.load': 'Stacked Oildrums',
        'marsarrowhead.airplane': 'marsarrowhead',
        'Box5MaxD.truck': 'Maximum Destruction w/Flextire',
        'JurassicAttack.truck': 'Jurassic Attack',
        'GGKRK02.truck': 'GGKRK02',
        '6a8cUID_door_train.fixed': 'Hall Doors',
        '05e7UID-nissan_skyline_R34.truck': 'Nissan Skyline GT-R 34 Police',
        'LAWICA-t813.truck': 'Airport Crashtender',
        '17c1UID-Legowrecker.truck': 'Lego wrecker',
        'sign-roundabout.fixed': 'sign-roundabout',
        '6032aUID-ss1.truck': 'Jeep Cherokee rally 2',
        'PomDrodafwrecker.truck': 'DAF Polish Wrecker',
        'SIIILW01.truck': 'Land Rover SIII Lightweight Animal',
        'bcdeabcf82f5aab4e3a964a47565c5a66f057be2-travego0.7.truck': 'Mercedes Travego',
        'badnews.truck': 'Bad News Travels Fast',
        'JeepBartoPL4.truck': 'Jeep Cherokee Wagoneer blue',
        'challenger.truck': 'Dodge Challenger',
        'ac500.truck': 'Terex-Demag AC500- 30m fixedjib',
        '0c0ecee99fd6c10a827a4a3d2c5f032b72e01470-trailer.load': 'Trailer with Hatch',
        '3434UID-MANTGS32350-LTF-Crane.truck': 'MAN TGS 32.350 with Liebherr LTF 1060',
        'Enigma.truck': 'MAN Caetano Enigma',
        'sign-noparking.fixed': 'sign-noparking',
        'mammoet-750t.load': 'Load (750tons)',
        'CH-47-AVI.airplane': 'Boeing CH-47 Aviation HIGH-FPS',
        'GraveDigger7.truck': 'Grave Digger VII',
        'c69ffUID-aflatbed.load': 'Ampliroll flatbed',
        'BigfootSnakeBite.truck': 'Snake Bite',
        'Scarletbandit.truck': 'Scarlet Bandit',
        'sign-leftturn.fixed': 'sign-leftturn',
        'Monster_truck.truck': 'Monster Truck 2',
        'Wrangler2.truck': 'Jeep Wrangler JK',
        'Audi80Quattro.truck': 'Audi 80 Quattro',
        '3804UID_rock01_10_stacked.load': 'rock01 10p stacked',
        '2c97UID-Manitou.truck': 'Manitou MLT 731',
        'd1ac11f8ca96956cd7fa5d20c0d9053c7b57fe58-Panther4x4.truck': 'Rosenbauer Panther 4x4',
        'sign-bluearrow2down.fixed': 'sign-bluearrow2down',
        'BigfootMS.truck': 'Ms. Bigfoot 11',
        'MMCP-DA.truck': 'Mitsubishi Pajero AT',
        '2008_KME_Predator.truck': '2008 KME Predator',
        'aa93UID_asrs.load': 'Automated storage and retrieval system',
        '5fab149cad2aaf6d9c5ec997534f0c9640f40f77-LHM280.truck': 'Liebherr LHM 280',
        'chevyambulance.truck': 'Chevrolet Ambulance',
        'Flak_Flatbed_Fire.load': 'Ampliroll Contanier Faltbed Fire',
        'ff57UID-wrecker.truck': '6x6 Scania Wrecker',
        'bcdeabcf82f5aab4e3a964a47565c5a66f057be2-skibox.load': 'Skibox (for Travego)',
        '3344UID-nachlaeufer.trailer': 'Selfsteering Trailer with Dolly',
        'gavrilbandit200b.truck': 'Gavril Bandit Stripped',
        'Premio.load': 'Burstner Premio',
        'IronOutlaw.truck': 'Iron Outlaw (Red)',
        'Incinerator.truck': 'Incinerator',
        'BoxUnimogMini1.truck': 'Unimog 406 Shorty w/arm crane',
        'Rear-end_Loader.trailer': 'refuse compactor',
        'afc4UID-a4e3UIDsprinter-brk-short.truck': 'Sprinter BRK KTW',
        '6153UID_blade_si.load': 'Mitsubishi MWT92 Wind Engine Rotor',
        'E-Maxx.truck': 'Traxxas E-Maxx',
        'Brutus.truck': 'Brutus',
        '93edUID-K100semiFlatt.truck': 'Kenworth K100 Semi FlatTop Full Fender',
        '7de7eUID_Rbns641.load': 'Rbns 641 freight car',
        'neoplan.truck': 'Bus Neoplan Starliner',
        'sign-leftpriority.fixed': 'sign-leftpriority',
        'Arch Winch.trailer': 'Arch Winch_2cables',
        'S10shortbed.truck': 'Chevrolet S10 Short Bed',
        'dfe998960108af42dc39924f23a315604ed0478e-larvitar379.truck': 'Larvitar 379',
        '53ftcontainer.load': '53ft container',
        'BulldozerRSCRC.truck': 'Bulldozer (Basl)',
        '6810cUID-chevs10offroad.truck': 'Chevrolet S10 Off-Road',
        'agoray.truck': 'Bus RVI Agora yellow',
        'MH_MTW.truck': 'Feuerwehr Marktheim MTW',
        'sennebogen55004.truck': 'SENNEBOGEN 5500  69.1m boom',
        'likkula.truck': 'Bus Neoplan Starliner Long',
        'NorthernNightmare.truck': 'Northern Nightmare',
        'cowboy.truck': 'Cowboy',
        'Kenworth.truck': 'Kenworth 5th wheel Log Truck',
        'a1b7UID_liebherr13hm.truck': 'Liebherr 13HM',
        'Stinger.truck': 'Stinger',
        'marsbeacon.load': 'marsbeacon',
        'bbkenwortht800_36.truck': 'Kenworth T800 tilt Flatbed long frame Tri-axle',
        'Maverik.truck': 'Maverik Monster Trakker',
        'MitCityCitaroN-mercedesCitaro.truck': 'Mercedes-Benz Citaro MitCity Bus',
        'gavril.truck': 'Gavril G2S',
        'sign-rocks.fixed': 'sign-rocks',
        'fa16d0a1f3b207f4c3b01ad510cc1aabc91f330e-peterbilt359ampliroll.truck': 'Peterbilt 359 Ampliroll',
        '7936f14a3cb385988ede498ed270791ec0a8e906-behemoth3.truck': 'Behemoth',
        'sign-bluearrow2left.fixed': 'sign-bluearrow2left',
        '6153UID_nacelle_si.load': 'Mitsubishi MWT92 Wind Engine Nacelle',
        'DestructibleBarricade4P.load': 'Destructible Barricade 4P',
        'Box5SledPull.load': 'Box5 Sledpull',
        'korppi-201011141613-nordiaexpress.boat': 'M/V Nordia Express',
        'gavrilzetar.truck': 'Gavril Zeta R',
        '45e43UID_SU-37-agile.airplane': 'SU-37 Agile',
        'EscaladeMonsterFT.truck': 'Escalade Monster Truck w/Flextire',
        'bbkenwortht800_35.truck': 'Kenworth T800W Daycab heavy haul tri-axle shorterframe',
        'CaptainAmerica.truck': 'Captain America',
        'burnsidepolice.truck': 'Burnside Police',
        'Scania_143H_6x4_box.truck': 'Scania 143H reefer Sties',
        'a1da0UID-bridge.fixed': 'Bridge',
        '180ton.load': '180ton ballast',
        '60a4613c1a5bcc786d6c82d0b1d59dbe9944aba0DAF_XF105_8x4.truck': 'DAF Firetruck Heavy Trans',
        '6810cUID-chevs10ashort.truck': 'Chevrolet S10 Short Bed',
        '3mt.trailer': 'Mr Phat',
        'ece03UIDbarge-bulk.boat': 'Barge (bulk)',
        '437a6f5153606e9896556b0ec84f0d332e714d33-CPOPS_renault_kerax.truck': 'Kerax Firetruck CP-OPS',
        'JBC-Ejector.trailer': 'JBC Ejector Trailer',
        'VW_T3_4x4_camo_normal.truck': 'VW T3 SYNCRO military with normal steering',
        'Viper.truck': 'Viper',
        '0854730f1cf0d0352995871d7a6d6809f568672e-trailmashercrane.truck': '6x6 Trail Masher w/ Crane',
        'GraveDiggerFT.truck': 'Gravedigger w/Flextire',
        '45foottrailer.trailer': '45 Foot Box Trailer',
        'a09eUID-skibox.load': 'Skibox (for Travego)',
        'RAZ2.truck': 'RAZ2',
        'SIIILW03.truck': 'Land Rover SIII Lightweight Total',
        '6230UID-AtegoDLK.truck': 'Mercedes-Benz Atego 1218 Ladder truck',
        '6ed2UID-an225.airplane': 'Antonov 225',
        'stabilizer.truck': 'Stabilizer',
        'YotaFlatbed.truck': '1980 Toyota Flatbed 4x4',
        'Magelys.truck': 'Irisbus Magelys',
        'US_boxcar_WP.load': 'Boxcar 40ft Western Pacific',
        'Terex-Demag AC500-2.truck': 'Terex-Demag AC500- 18m fixedjib',
        'sign-pulloff.fixed': 'sign-pulloff',
        'HH_RTW.truck': 'Fire Department Hamburg Ambulance',
        'MarsSC.airplane': 'MarsSC',
        '6a8cUID_demag_train.load': 'DEMAG ZKKE Train',
        'sign-nohazmat.fixed': 'sign-nohazmat',
        'Box5DeuceCargo.truck': 'Deuce and a Half Cargo - Box5',
        'MH_DLK.truck': 'Feuerwehr Marktheim DLK 23 12',
        'bbkenwortht800_16.truck': 'Kenworth T800W sleeper tri-axle longframe heavy haul',
        'teamsuzuki.truck': 'Team Suzuki',
        'sign-warning.fixed': 'sign-warning',
        'rallyxbarrier01a.load': 'Armco Barrier 4M',
        'aa21bUID-AST-1X.truck': 'AST-1X',
        'Firepeterbilt359-long.truck': 'Firepete (long)',
        'be8ffac24d8ce0c29ddb05b5781aa26e50c73119-StockVolvo245.truck': 'Volvo 245 (Wagon)',
        'MaxD3.truck': 'Maximum Destruction (Christensen)',
        'hottamale.truck': 'Hot Tamale',
        'GravediggerXXp.truck': 'Grave Digger XX (Purple)',
        '57611UIDmidibus-si.truck': 'Starling Island Midibus P30',
        'Rhinofoshow.truck': 'Yamaha Rhino (Show)',
        'afc4UID-a4e3UIDsprinterthwmtw.truck': 'Sprinter van THW MTW',
        '1312UID-mantgx26480semi.truck': 'MAN TGX 26.480 Semi RHD',
        'b2a8e189077fab095dfa98595abb5520be56b1ee_AE86.truck': 'Toyota Trueno AE86',
        'fox1067.truck': '106.7 The Fox',
        '1312UID-mantgx18440semi.truck': 'MAN TGX 18.440 Semi',
        '6a8cUID_1_demag_southeast.load': 'DEMAG ZKKE southeast',
        '182bUID-MML2012.truck': 'Mitsubishi L200 DI-D Dakar',
        'sennebogen5500jib2.truck': 'SENNEBOGEN 5500 24.3m boom 46.7mjib',
        'GeneralTire.truck': 'General Tire',
        'caboverpete.truck': 'Peterbilt 362 Cabover',
        'EltorolocoWilman.truck': 'El Toro Loco (Werner)',
        'rail1tPnt190r634dR.fixed': 'Railroad Switch 190r 6.34d r',
        'bbkenwortht800_10.truck': 'Kenworth T800 daycab short frame',
        'susmonopoint.trailer': 'Suspeneded Monorail System Points',
        'sn_coaster.truck': 'Roller Coaster Thingamajig',
        'Shockwave.truck': 'Shockwave',
        'a-mammoet.load': 'Ampliroll (10tons)',
        'raminator.truck': 'Raminator',
        'GraveDiggerXII.truck': 'Grave Digger XII',
        'agg300.truck': 'Van Hool AGG 300',
        'VW_T3_4x4_normal .truck': 'VW T3 SYNCRO with normal steering',
        'highdefchallenger.truck': 'high def chally',
        'f719UID-Ategowrecker.truck': 'Mercedes-Benz Atego 818 tilt tray wrecker',
        'crushstation.truck': 'Crushstation',
        'fouroildrums.load': 'Four Oildrums',
        'Firepeterbilt359.truck': 'Firepete',
        '0a77fUID_ds9_trailer_interface.truck': 'DS9 Submarine-Trailer-Interface',
        '0c0ecee99fd6c10a827a4a3d2c5f032b72e01470-volvo_fl6_hatch.truck': 'Volvo FL6 with hatch',
        '45e43UID_SU-37-blue.airplane': 'SU-37 Blue',
        'spidertrax1.truck': 'Spidertrax Crawler | Stock',
        'ural4320.truck': 'Ural 4320',
        '57611UIDsprinter-si-ambulance.truck': 'Starling Island Ambulance Sprinter',
        '6ed2UID-an225lite.airplane': 'Antonov 225 Lite Version',
        '6ef84UID-1stgen2.truck': '1st Gen Dodge Cummins Wrecker',
        'monstermagic.truck': 'Monster Magic',
        'barricade.load': 'barricade',
        'warwizard.truck': 'War Wizard',
        'IceCreamMan.truck': 'Ice Cream Man',
        '6a8cUID_1_demag_northwest.load': 'DEMAG ZKKE northwest',
        'Audi80_18fwd.truck': 'Audi 80 1.8 FWD',
        'CaliforniaKid.truck': 'California Kid',
        'timeflys.truck': 'Time Flys',
        'Pastrana.truck': 'Pastrana 199',
        'GravediggerXXg.truck': 'Grave Digger XX (Green)',
        'gavrilomega.truck': 'Gavril Omega Ten',
        'ac500withssl.truck': 'Terex-Demag AC500- with ssl',
        '701c0b1d867d1ecd5eedd78315fd7d7972ee3d98-skyvan.airplane': 'Skyvan',
        'US_boxcar_UP.load': 'Boxcar 40ft Union Pacific',
        'a352aUID-K100semiFlatt.truck': 'Kenworth K100 Semi FlatTop Full Fender',
        'NastyBoy.truck': 'Nasty Boy',
        'rail1tPnt150r10dL.fixed': 'Railroad Switch l',
        'Flak_Flatbed.load': 'Ampliroll Contanier Faltbed With Wheels',
        'ff57UID-Scanialoader.truck': '6x6 Scania Loader',
        'Wolverine.truck': 'Wolverine',
        'skstep.trailer': 'stepdeck custom sk',
        'Summit2011Bigfoot16.truck': 'Summit Bigfoot 2011',
        'da2d4UID-ss1.truck': 'Jeep Cherokee rally 4',
        'Larvkran-Superlift-CW-Trailer-520t.load': 'FLK-1500 superlift-trailer ballast (520t)',
        'tracktestv15.truck': 'Tracked_vehicle_with_slidenodes_v15',
        '07366UID-oshkoshloader.truck': 'Oshkosh LVRS boat loader',
        '184cUID-panther4x4.truck': 'Rosenbauer Panther 4x4',
        'sennebogen55001.truck': 'SENNEBOGEN 5500  35.5m boom',
        'sprinterStrazambulance.truck': 'Mercedes Sprinter Fire Dept PL',
        'WoodenCrate_SOVIET.load': 'Wooden Crate (SOVIET)',
        '0d570UID-DodgeChargerv2-contactive.truck': 'Dodge Charger v2 contactive',
        'ple002_SuperBus.truck': '\'Starbus\' Concept Bus',
        'gavrilzetax.truck': 'Gavril Zeta X',
        'SIIILW06.truck': 'Land Rover SIII Lightweight Camo',
        'arwaymobi.truck': 'Irisbus Arway Mobilien',
        'FiredUp.truck': 'Fired Up',
        'fireequip.trailer': 'Fireequip',
        'sennebogen5500jib6.truck': 'SENNEBOGEN 5500  46.7m boom 46.7m jib',
        'eradicator.truck': 'Eradicator',
        'SuddenImpact.truck': 'Sudden Impact',
        'agoraw.truck': 'Bus RVI Agora white',
        '4f5aUIDContainerChassis-preloaded.trailer': 'Krone Box Liner loaded',
        'oildrum.load': 'Oildrum',
        'BlazerSlideNode.truck': 'Blazer Slidenode',
        'sign-menatwork.fixed': 'sign-menatwork',
        'mammoet-10t.load': 'Load (10tons)',
        'sqwrecker.truck': '6x6 sqwrecker',
        'gavrilb.truck': 'Gavril G2',
        'Instigator.truck': 'Instigator',
        '07366UID-C1-trans.trailer': 'C1 Transporter',
        'Saviem_S53.truck': 'Saviem S53',
        'MAN_F2000_box_6X2.truck': 'MAN F2000 Evo Dry Van 6X4 (26.464)',
        'goldhofer_modul_3.trailer': 'Goldhofer THP/ET G+4+B+4 (auto steer)',
        'sign-blueleftturn.fixed': 'sign-blueleftturn',
        'shocktherapy.truck': 'Shock Therapy',
        '60ton.load': '60ton ballast',
        'MM-Monster-200-LS.truck': 'MeanMachine-Monster-200-LS',
        'tanktrailer.load': 'Small Tank Trailer',
        'a09eUID-travego0.7.truck': 'Mercedes Travego',
        'a09eUID-travego0.7B.truck': 'Mercedes Travego BeachTours',
        'gavrilmz2r.truck': 'Gavril MZ2R',
        'squishybigfoot.truck': 'Squishy Bigfoot w/Flextire',
        'sennebogen5500jib.truck': 'SENNEBOGEN 5500 24.3m boom 24.3mjib',
        'HurricaneForce.truck': 'Hurricane Force',
        'sign-maxspeed60.fixed': 'sign-maxspeed60',
        'c69ffUID-acontainer.load': 'Ampliroll container (15tons)',
        'sign-blueroundabout.fixed': 'sign-blueroundabout',
        'ple003_zil135uragan.truck': 'ZIL-135 9P140 Uragan',
        'sign-tunnel.fixed': 'sign-tunnel',
        'sq_police.truck': '4x4 sq Police',
        'sign-priorityintersection.fixed': 'sign-priorityintersection',
        'RedBaron.truck': 'Red Baron',
        'bbkenwortht800_33.truck': 'Kenworth T800 dump truck 2 axle',
        'GravediggerXXII.truck': 'Grave Digger XXII',
        '49ford.truck': '1949 Ford Club Coupe',
        'burnsidelimo.truck': 'Burnside Limousine',
        'houseboat.boat': 'Houseboat',
        'Blacksmith.truck': 'Blacksmith',
        '3156b13de86dcf8384a128ea32f5ec029cf4066bflatdaf.truck': 'DAF Civil Defense',
        'bbkenwortht800_19.truck': 'Kenworth T800W sleeper two-axle longframe',
        '2c97UID-Forklift.load': 'Manitou Forklift',
        '496aUID-bouy.load': 'Bouy',
        'accord.truck': 'Honda Accord Hatchback',
        'bbkenwortht800_3.truck': 'Kenworth T800 Extended Flatbed tri-axle',
        '68f9UID-chemicaltrailer.trailer': 'Chemical Trailer',
        'gavrilbanditoffroad.truck': 'Gavril Bandit Off-Road',
        'burnsideoffroad.truck': 'Burnside Off-Road',
        '0008UID_pallet2000.load': 'EUR-pallet loaded 2000kg',
        'gavrilomegasix.truck': 'Gavril Omega Six',
        'YotaLongBed1.truck': '1980 Toyota Longbed 4x4 (flex-tires)',
        'gavrilbandit200.truck': 'Gavril Bandit 200',
        'bbkenwortht800_32.truck': 'Kenworth T800 two axle boxtruck',
        'burnsidetaxi.truck': 'Burnside Taxi',
        'MarsTC.airplane': 'MarsTC',
        'BlueThunder.truck': 'Blue Thunder',
        '686eUID-ovaltesttrack.load': 'Oval Railroad Slidenode Testtrack',
        '686eUID-Electroliner.truck': 'CNS&M Electroliner',
        't800.truck': 'Kenworth T800',
        'GravediggerXV.truck': 'Grave Digger XV',
        'sign-bluearrowdownleft.fixed': 'sign-bluearrowdownleft',
        '3804UID_rock01_1.load': 'rock01',
        '7e75UID-ALP-45DP_electric.truck': 'Bombardier ALP-45DP (electric mode)',
        'sign-maxspeed20.fixed': 'sign-maxspeed20',
        'FLK-1500-longboom.truck': 'AinTech FLK-1500 108m',
        'sign-rightturn.fixed': 'sign-rightturn',
        'BBD-LTM-1095-container.load': 'Binsell Container (7t)',
        'ferrari-testarossa.truck': 'ferrari testarossa',
        'CH-54-Skycrane.airplane': 'CH-54 Skycrane',
        '0d570UID-DodgeCharger.truck': 'Dodge Charger (beta)',
        'WoodenCrate_UN.load': 'Wooden Crate (UN)',
        'oil_filter_89ton.load': 'oil filter 89 ton',
        'AfterBurnerFT.truck': 'AfterBurner w/Flextire',
        '0a77fUID_simsub01_v13_fps_level1.boat': 'DS9 Scientiffic Submarine (fps level 1)',
        '1ab4UID-MTVRcabchassis.truck': 'MTVR Cab Chassis',
        'VW_T3_4x4_camo_RWsteer.truck': 'VW T3 SYNCRO military with RW-steering',
        'JeepBartoPL.truck': 'Jeep Cherokee Grey',
        'US_watertanker.load': 'Watertanker 40ft',
        'e9e800deee5bab54816a82baf4eb0275368f43f9-trailer.trailer': 'Trailer with cooler',
        '6a8cUID_1_demag_hall.load': 'DEMAG ZKKE Hall',
        'Box69CamaroDragster.truck': 'Box 1969 Camaro Dragster',
        'thefelon.truck': 'The Felon',
        'K100lowboy.trailer': 'K100 Lowboy',
        'Desert_Trails-SoundLoad.fixed': 'SoundLoad',
        'Toxic.truck': 'Toxic',
        'JeepFireDept.truck': 'Jeep Cherokee FireDept',
        'Melroe_M880.truck': 'Melroe M880 Prime Mover',
        'a352aUID-K100semi.truck': 'Kenworth K100 Semi Workhorse',
        'burnsiderace.truck': 'Burnside Race',
        'sign-autobahnend.fixed': 'sign-autobahnend',
        'log2.load': 'Log (21T)',
        'ebfdUID-t813.truck': '8x8 Tatra T813',
        'taz.truck': 'Tasmanian Devil',
        'BlackStallion.truck': 'Black Stallion',
        'sign-notrucks.fixed': 'sign-notrucks',
        '120ton.load': '120ton ballast',
        'Unimog406trials.truck': 'Unimog 406 Truck Trial',
        'Grinder2.truck': 'Grinder (Krmel)',
        'gavrilzetalwb.truck': 'Gavril Zeta LWB',
        'IronMan2.truck': 'Iron Man (Buetow)',
        '0854730f1cf0d0352995871d7a6d6809f568672e-trailmasher.truck': '6x6 Trail Masher',
        '6squishycrushcarsrg.load': '6 Crushable Cars (red and green)',
        'BoxDodgeRamTruggyFTcollision.truck': 'Box Dodge Cummins Truggy Collision (FlexTire)',
        '167231cfc8f8ade1fdf81effd2c91e68cf743d23-man_tga.truck': '8x8 MAN-TGA',
        'tourlinerL.truck': ';V 1.0',
        '3344UID-pipe.load': 'Pipe load 38.5m',
        'BigfootMLB.truck': 'Bigfoot 10 MLB',
        'BoxDodgeRamEXTboggerCollision.truck': 'Box Dodge Cummins Ext.Cab 12v bogger',
        'BoxDodgeRamEXT.truck': 'Box Dodge Cummins Ext.Cab 12v',
        'HH_HLF.truck': 'Fire Department Hamburg Fire Engine',
        'Larvkran-Superlift-CW-280t.load': 'FLK-1500 superlift ballast (280t)',
        'susmonopassenger.truck': 'Suspended Monorail Train 4 Car Passenger',
        'd1ac11f8ca96956cd7fa5d20c0d9053c7b57fe58-Panther8x8HRET.truck': 'Rosenbauer Panther 8x8 HRET',
        'Tailgator.truck': 'Tail Gator',
        'Box5W900R.truck': 'Box5 W900 Rollback',
        'sign-yield.fixed': 'sign-yield',
        'b62eUID-hilux.truck': 'Toyota Hilux mod',
        'RazinKane.truck': 'Razin Kane',
        'be8ffac24d8ce0c29ddb05b5781aa26e50c73119-RaceVolvo240.truck': 'Badass Volvo 240',
        'Predator.truck': 'Predator',
        'JeepWranglerUnlimited-(OFFROAD)-HardTop.truck': 'Jeep Wrangler Unlimited-HardTop(Offroad)',
        'FRS.truck': 'FRS  (ambulance) V3',
        'Container20ftDry.load': 'Std 20ft Dry Container',
        'sign-maxspeed90.fixed': 'sign-maxspeed90',
        'rail1tPnt190r634dLi.fixed': 'Railroad Switch 190r 6.34d li',
        'sign-autostrasse.fixed': 'sign-autostrasse',
        'mobile_ramp.load': 'Mobile Ramp',
        'pouncer.truck': 'Pouncer',
        '46a6UID-FlxibleMetroD.truck': 'Flxible Metro D',
        'bbkenwortht800_1.truck': 'Kenworth T800W tri-axle Daycab longframe',
        'bbkenwortht800_14.truck': 'Kenworth T800W toolbox tri-axle Daycab longframe',
        'sign-parkingzonestart.fixed': 'sign-parkingzonestart',
        'CH-47-SAR.airplane': 'Boeing CH-47 SAR',
        'Nordstern.boat': 'Passenger Ship MS North Star',
        'marsdodge.truck': 'marsdodge',
        'MTVRFire.truck': 'MTVR Fire Engine',
        'Maniac.truck': 'Maniac',
        '514cc6721149db473b7cb5916b0dae639d6811fc-hysterforklift.truck': 'Hyster Forklift',
        'FDNYTruck.truck': 'FDNY Monster Truck',
        'squishycrushbus.load': 'Crushable stack (car > bus > bus > car)',
        'gavrilbanditextreme.truck': 'Gavril Bandit Extreme',
        'simba_8x8.truck': 'Simba 8x8',
        'AMTweight.load': 'AMT spare counterweight 10t',
        'airafterburner.truck': 'U.S Air Force Afterburner',
        '6153UID_base.load': 'Mitsubishi MWT92 Wind Engine Base',
        'bbkenwortht800_18.truck': 'Kenworth T800 dumptruck 4th axle',
        '24a159b6dc749abb4a38edbaef41f90d0229c2ee-LTM-1050.truck': 'Liebherr LTM 1050-3.1',
        'Obsession.truck': 'Obsession',
        'Bigfoot16.truck': 'Bigfoot 16 Summit',
        'Samson.truck': 'Samson',
        'Flak_Medium.load': 'Ampliroll Contanier Medium',
        '852330c5fa103d1e3f281a346dfc5da59e653fbf-renault_express_monster.truck': 'Renault Express Monster Truck',
        'sign-maxspeed130.fixed': 'sign-maxspeed130',
        '07366UID-C1-tunnel-WIP.load': 'C1 Offshore WIP working rudder F7 F8',
        '6a8cUID_demag_column.load': 'DEMAG ZKKE Column',
        '0a77fUID_simsub01_v13_fps_level3.boat': 'DS9 Scientiffic Submarine (fps level 3)',
        'BoxDodgeRamTruggyCollision.truck': 'Box Dodge Cummins Truggy Collision',
        '2f52b1cde41ebd433c32da74ee2148c6c51a3672_p38_lightning.airplane': 'P-38 Lightning V1',
        'WoodenCrate_IKEA.load': 'Wooden Crate (IKEA)',
        'sign-nopedestrians.fixed': 'sign-nopedestrians',
        'Ford_F450_Super_Duty.truck': '2008 Ford Super Duty',
        'e9e800deee5bab54816a82baf4eb0275368f43f9-goeiemoggel.truck': 'Volvo FL6 with cooler',
        'sign-hospital.fixed': 'sign-hospital',
        'sqspecial.truck': 'Volvo FL12 Firetruck  s&q special',
        '14b8UID-767shocks.airplane': '767 AA Airliner',
        'MH_TLF1625.truck': 'Feuerwehr Marktheim TLF 16/25',
        'c5b5UID-ScaniaR420TL.truck': 'Scania R420 Topline 4x2',
        '1ab4UID-MTVR.truck': 'MTVR Cargo',
        '6ef84UID-1stgen1.truck': '1st gen dodge cummins bumper pull',
        '7a6eUID-flyjib.load': 'Flyjib for Knuckleboom Crane',
        'Stonecrusher2.truck': 'Stone Crusher (Kane)',
        'bbkenwortht800_29.truck': 'Kenworth T800 longer Tanker',
        '160ton.load': '160ton ballast',
        'Box5W900fps.truck': 'Box5 W900 Flatop Sleeper Not Shiny',
        'Box69CamaroBlue.truck': 'Box 1969 Camaro BlueGrass',
        'beacon.truck': 'marsbeacon',
        '6153UID_tower_carrier.load': 'Mitsubishi MWT92 Wind Engine Tower Carrier',
        'JeepBartoPL_Creak.truck': 'Jeep Cherokee tuned by Creak',
        'iep-countypolice.truck': 'County Police (Chally)',
        'Batman.truck': 'Batman',
        'Class58.truck': 'Class 58',
        'SonuvaDigger.truck': 'Son-Uva Digger',
        'MH_ELW.truck': 'Feuerwehr Marktheim ELW 1',
        '7a6eUID-mantgx26540ballastboxcrane.truck': 'MAN TGX 26.540 truck with crane and ballastbox',
        'AngerManagement.truck': 'Anger Management',
        'jeepcherokee.truck': 'Jeep Cherokee Crawler',
        'Rhino.truck': 'Yamaha Rhino',
        'Box69CamaroSilverFPS.truck': 'Box 1969 Camaro Silverback FPS',
        'Farmwindtop.trailer': 'Farm Windmill',
        '3344UID-woodload.load': 'Wood load 20m',
        'BigDawg.truck': 'Big Dawg',
        'geterdone.truck': 'Get Er Done',
        '15096a518303dcc2783f624caf9234eb84bdbda6wrecker.truck': 'Scania Firetruck Wrecker',
        'sign-bluearrow2up.fixed': 'sign-bluearrow2up',
        'sign-maxspeed70.fixed': 'sign-maxspeed70',
        'US_flatcar_brown.load': 'Flatcar 40ft brown',
        'sign-maxspeed10.fixed': 'sign-maxspeed10',
        '6a8cUID_1_demag_column.load': 'DEMAG ZKKE Column',
        'ice-forklift2.truck': 'hyster top spreader',
        '476cUID-otter.airplane': 'twin otter',
        'BoxDodgeRamTruggy.truck': 'Box Dodge Cummins Truggy',
        'MH_LF8.truck': 'Feuerwehr Marktheim Ortsfeuerwehr Oberdorf LF 8',
        'bf1c7f63c2560fa67707e73f05f147a1a6ac3b32truckcamper.load': 'Truck Camper',
        'bbkenwortht800_8.truck': 'Kenworth T800 6x6 Flatbed regular frame',
        'bbkenwortht800_38.truck': 'Kenworth T800W sleeper heavy haul 4-axle heavyframe',
        'rail1tPnt190r634dtri.fixed': 'Railroad Switch 190r 6.34d tri',
        'hilux.truck': 'Toyota Hilux',
        'Container40ftDry.load': 'Std 40ft Dry Container',
        'AC500with36mluffingjib2.truck': 'Terex-Demag AC500- 36m luffing jib',
        'krazytrain.truck': 'Krazy Train',
        '1af9UID-concorde4350UID.airplane': 'Concorde',
        'bbkenwortht800_7.truck': 'Kenworth T800 Flatbed short frame',
        'MTVR.truck': 'MTVR Cargo',
        'sennebogen5500.truck': 'SENNEBOGEN 5500 24.3m boom',
        'f734UID-dodgepolice.truck': 'Dodge Police Car',
        'mod_platform_dollyrearmiddle.load': 'modulare platform rear middle',
        'metalmulisha.truck': 'Metal Mulisha',
        'HigherEducation.truck': 'Higher Education',
        'Bigfoot19.truck': 'Bigfoot 19',
        'e35cc35e79a92cbbd66ebfba3be7f906c91e3536-sprinterrtw.truck': 'RTW Feuerwehr Essen',
        'EscaladeMonsterRWS.truck': 'Escalade Monster Truck w/aux RWS',
        'bbkenwortht800_13.truck': 'Kenworth T800 boxtruck 4th axle',
        '7517UID-bobcats130balespear.truck': 'Bobcat S130 with Bale Spear Attachment',
        'MonsterEnergy.truck': 'Monster Energy',
        'CE-300.truck': 'CE-300',
        'excaliber.truck': 'Excaliber',
        'journey.truck': 'mcd Journey 1.0',
        '4b54a5a3bcc68b1f496cdd827ad44b841e36faaa-firetruck.truck': 'Volvo FL12 Firetruck Pumper',
        'BigHaulerGooseneck.load': 'BigHaul Gooseneck',
        '0008UID_pallet1500.load': 'EUR-pallet loaded 1500kg',
        'Liebherr-630-ECH.truck': 'Liebherr 630-EC-H(beta)3',
        '49fordtudor.truck': '1949 Ford Tudor',
        'PL_volvo_fl6_hatch.truck': 'Volvo FL6 Firetruck IGS PL',
        'sign-stop.fixed': 'sign-stop',
        'accordb.truck': 'Honda Accord Hatchback Extrem Tunning',
        'Shocker.truck': 'Shocker',
        'gavrilmz2.truck': 'Gavril MZ2',
        'BoxUnimogTrials.truck': 'Unimog 406 Trials',
        'rail1tPnt190r634dL.fixed': 'Railroad Switch 190r 6.34d l',
        't800extended.truck': 'Kenworth T800 Extended',
        'spiderman.truck': 'Spiderman',
        'rapattack.truck': 'Rap Attack',
        'GravediggerXIX.truck': 'Grave Digger XIX',
        'SwampThing.truck': 'Swamp Thing',
        '0008UID_pallet750.load': 'EUR-pallet loaded 750kg',
        'equalizer.truck': 'Equalizer',
        'BoxUnimogMini.truck': 'Unimog 406 Shory',
        '0008UID_palletfork.load': 'Pallet Fork',
        'Nitemare.truck': 'Nitemare',
        '0a77fUID_simsub01_v13_fps_level2.boat': 'DS9 Scientiffic Submarine (fps level 2)',
        'sign-bluerightturn.fixed': 'sign-bluerightturn',
        'SIIILWLP.truck': 'Land Rover SIII Lightweight LP',
        'Airdog.truck': 'Airdog',
        'GroundPounder.truck': 'Ground Pounder',
        'sign-bluearrowdownright.fixed': 'sign-bluearrowdownright',
        'bbkenwortht800_5.truck': 'Kenworth T800 6x4 Tanker',
        'accordc.truck': 'Honda Accord Hatchback Rallye',
        '46a6UID-FlxibleMetroD_speed.truck': 'Flxible Metro D Improved',
        'canadair_AN12.airplane': 'Antonov 12 Canadair(FireFighter)',
        '45e43UID_SU-37-speedy.airplane': 'SU-37 Speedy',
        'vwbeetle.truck': 'VW Beetle',
        'rallyxbarrier01b.load': 'Armco Barrier 8M',
        'rail1tPnt190r10dR.fixed': 'Railroad Switch r',
        '3252UID-lexus.truck': 'Lexus LS430',
        'tropicalthund.truck': 'Tropical Thunder',
        'a355ad6aa983fc025e5341ff77988fa229ea35a2-firetruck.truck': 'DAF Firetruck watertank',
        'PR100.truck': 'Renault PR100',
        'spitfire.truck': 'Spitfire',
        'RipSaw.truck': 'Box5 Rip Saw',
        'Box5W900D.truck': 'Box5 W900 Daycab',
        'Monstermuttdalm.truck': 'Monster Mutt Dalmation',
        'BoxSamuraiExo.truck': '?Box5 Suzuki Samurai ExoCage',
        'containertruck.truck': 'Container Forklift',
        'BigfootBadBoy.truck': 'Bigfoot 14 Bad Boy',
        'KingKrunch.truck': 'King Krunch',
        'boogie.truck': 'boogie mcd v2.0',
        '6153UID_hub.load': 'Mitsubishi MWT92 Wind Engine Rotor Hub with Carrier',
        '57611UIDsprinter-si-muniworks.truck': 'Starling Island Municipal Works Sprinter',
        't815-firetruck.truck': 'Tatra 815 6X4 firetruck',
        'sign-roadnarrowsleft.fixed': 'sign-roadnarrowsleft',
        'sign-autostrasseend.fixed': 'sign-autostrasseend',
        'susmonogoods.truck': 'Suspended Monorail Train 4 Car Goods',
        'Kenworth6x4.truck': 'Kenworth 6x4 5th Wheel Log Truck',
        'PR100rtm.truck': 'Renault PR100 RTM',
        'Terex-Demag AC500-2 met JIB.truck': 'Terex-Demag AC500- 90m luffing jib',
        'b77390b72b40492e54617d10caf831781abbd745-safari.truck': '2009 Chevrolet Safari LS',
        '7d7b8de9d56b9d9503c95573e44629dbe5648180-tanker-3axle.trailer': 'Tanker 3 axle',
        'c5b5UID-ScaniaR470TL.truck': 'Scania R Topline 4x2',
        'ece03UIDbarge-liquid.boat': 'Barge (liquid goods)',
        't2000.truck': 'Kenworth T2000',
        '7d7b8de9d56b9d9503c95573e44629dbe5648180-tanker-2axle.trailer': 'Tanker 2 axle',
        'bc274690ed7d553489b56f4209ecbdbacb71e0c1-cement.trailer': 'Cement Trailer',
        '0c6f51e45f0595935ed4356ef032f95bf3f4e892daf.truck': 'DAF Federal Police CP-OPS',
        'PeelP50White.truck': 'Peel P50 White',
        'Mountaineer.truck': 'Mountaineer',
        'sign-crossingnear.fixed': 'sign-crossingnear',
        'BulldozerPEI.truck': 'Bulldozer (McDonough)',
        '852330c5fa103d1e3f281a346dfc5da59e653fbf-renault_hearse.truck': 'Renault Express Stretched Hearse',
        'Destroyer.truck': 'Destroyer',
        'mammoet-250t.load': 'Load (250tons)',
        '470bUID-renault.truck': '4x4 Terrain editor truck',
        'agora_sd.truck': 'Bus RVI Agora S (working doors)',
        '59aeUID-small_sweeper.truck': 'Small sweeper',
        'SIIILW02.truck': 'Land Rover SIII Lightweight Camburg',
        'JeepFire.truck': 'Jeep Cherokee Fire',
        'sennebogen55002.truck': 'SENNEBOGEN 5500  46.7m boom',
        'AmericanGuardian.truck': 'American Guardian',
        'tourliner-skibox.load': ';V 1.0',
        'challengerusty.truck': 'rusty chally',
        '6153UID_tower3.load': 'Mitsubishi MWT92 Wind Engine Tower 3',
        'F1.truck': 'F1 Ferrari',
        'burnsidedrag.truck': 'Burnside Drag',
        'tourliner.truck': ';V 1.0',
        'ebe2UID-Legocar.truck': 'Lego car 4x4',
        'HeavyHitter.truck': 'Heavy Hitter',
        'sign-roadnarrows.fixed': 'sign-roadnarrows',
        'Monstermutt.truck': 'Monster Mutt (Miller)',
        'safeauto.truck': 'Safe Auto Minimizer',
        '0008UID_pallet500.load': 'EUR-pallet loaded 500kg',
        '589aUID_Container-Ship-Cargo-Princess.boat': 'Container-Ship-Cargo-Princess',
        '0d570UID-DodgeCharger-v2.truck': 'Dodge Charger v2',
        '45e43UID_SU-37.airplane': 'SU-37',
        'bbkenwortht800_20.truck': 'Kenworth T800 2 axle Extended Flatbed',
        'WoodenCrate_OSB.load': 'Wooden Crate (OSB)',
        '6a8cUID_1_demag_southwest.load': 'DEMAG ZKKE southwest',
        '95bbUID-agoras.truck': 'Bus RVI Agora S',
        'sign-blueYright.fixed': 'sign-blueYright',
        '80429078e6da5d05f4f1b210d782985aa3d48c71stepvan.truck': 'Chevrolet IPS Stepvan',
        'theturtle4.truck': 'The Turtle 4.0',
        'Tilt_deck.trailer': 'Tilt deck tag trailer',
        'agorag.truck': 'Bus RVI Agora green',
        'M2DCamo.truck': 'M2D Camo Thunder',
        'RTW2_FW.truck': 'Sprinter RTW',
        'Box69CamaroSilver.truck': 'Box 1969 Camaro Silverback',
        'bf1c7f63c2560fa67707e73f05f147a1a6ac3b3294Dodge_camper.truck': '94Dodge with Camper Mounts',
        'ds9_research_vessel_v4.78.boat': 'DS9 research vessel v4.78',
        'sign-bluebuslanes.fixed': 'sign-bluebuslanes',
        '2128UID-flatdaf.truck': '4x6 crane flatbed',
        '57611UIDweasel-si.boat': 'Starling Island Weasel Rescue Boat',
        'mod_platform_front_middle.load': 'modulare platform front middle',
        'burnside.truck': 'Burnside',
        'deff0c16bce7525a4575c92d269c8f66126f9fc8-t813.truck': 'Airport Crashtender',
        'Ford_F550_Crawler.truck': 'Ford F550 Super Duty crawler',
        'a-rocket.load': 'Skinned Rocket',
        'testruck.truck': 'testruck_flexwheel',
        'WreckingCrew.truck': 'Wrecking Crew',
        '7e2df6237ed314ae05ca8786d91f071d325e8003ampliroll.truck': 'Volvo 8X8 Firetruck Ampliroll',
        '69d1f86083cd690d6277d44db1065e527ec0639f-ampliroll6x6.truck': 'DAF 6X6 Firetruck ampliroll',
        'sign-derestriction.fixed': 'sign-derestriction',
        'MTVRdumpbed.truck': 'MTVR Dumpbed',
        '5b95UID-ss1.truck': 'Jeep Cherokee rally 3',
        'aftershocknew.truck': 'Aftershock',
        '4x4mercflatbed.truck': '4X4 merc 1317 Flatbed',
        'Grinder3.truck': 'Grinder (Seasock)',
        'GravediggerXXIII.truck': 'Grave Digger XXIII',
        '4x4mercsnow.truck': '4X4 merc1317 gritter',
        '726fUID-dodgepolice.truck': 'Dodge Police',
        'US_MOW_gondola.load': 'MOW Gondola 40ft',
        'BlazerPreTest.truck': 'Blazer Pre-Test',
        'WoodenCrate_DHL.load': 'Wooden Crate (DHL)',
        'be8ffac24d8ce0c29ddb05b5781aa26e50c73119-StockVolvo240.truck': 'Standard Volvo 240',
        'BoxDodgeRam.truck': 'Box Dodge Cummins 12v',
        'af25UID-aaadodgeviper.truck': 'Dodge Viper',
        'MartialLaw.truck': 'Martial Law',
        'US_flatcar_yellow.load': 'Flatcar 40ft yellow',
        'zetor.truck': 'Zetor 16 245',
        'dodge.truck': 'Dodge Pickup',
        'a352aUID-K100semiFlat.truck': 'Kenworth K100 Semi FlatTop',
        'expie.truck': 'Ford Expedition',
        '6153UID_nacelle.load': 'Mitsubishi MWT92 Wind Engine Nacelle with Carrier',
        'be428a3bdabde161a973cacf0b05f8db19db7348-p359_4x2.truck': 'Peterbilt 359 4x2',
        'sign-noentry.fixed': 'sign-noentry',
        'sign-nostopping.fixed': 'sign-nostopping',
        '514cc6721149db473b7cb5916b0dae639d6811fc-forklift.load': 'Forklift crate',
        'Box5DeuceBobbed.truck': 'Deuce and a Half Bobbed - Box5',
        'CH-47-LOG.airplane': 'Boeing CH-47 LOGGER',
        'JeepFBI.truck': 'Jeep Cherokee FBI',
        'WoodenCrate_TNT.load': 'Wooden Crate (TNT)',
        'c75c0UID-finnexpress.boat': 'M/V Finnexpress',
        'Barbarian.truck': 'Barbarian',
        'Bigfoot18.truck': 'Bigfoot 18',
        'squishyindy.truck': 'Indy Crawler',
        'sign-crossingmedium.fixed': 'sign-crossingmedium',
        'dfe998960108af42dc39924f23a315604ed0478e-tyranitar379.truck': 'Tyranitar 379',
        '3dc2eUID-MM-Monster-200-LS.truck': 'MeanMachine-Monster-200-LS',
        'Liebherr_LTC_1045.truck': 'Liebherr LTC 1045',
        'bumper weight.load': 'bumper weight for kenworth heavuy haul',
        'sign-maxspeed40.fixed': 'sign-maxspeed40',
        'JeepNYPD.truck': 'Jeep Cherokee NYPD',
        'arwaytibus.truck': 'Irisbus Arway Ti\'bus',
        'CaravanRallyGT.load': 'Caravan Rally GT',
        'squishycjflextire.truck': 'Jeep CJ Custom Crawler (flex tire)',
        '852330c5fa103d1e3f281a346dfc5da59e653fbf-renault_express.truck': 'Renault Express',
        '24a159b6dc749abb4a38edbaef41f90d0229c2ee-ltm1095.truck': 'Liebherr LTM 1095-5.1',
        'ViperGTS.car': 'Dodge Viper GTS',
        'ViperGTS_Race.car': 'Dodge Viper GTS (Race)',
        'Chevrolet-G30-Camper.truck': 'Chevrolet G30 Camper',
        'Chevrolet-G30-Ambulance-v2.truck': 'Chevrolet G30 Ambulance',
        '1988AudiQuattro.car': '1988 Audi Quattro',
        '1988AudiQuattroRally.car': '1988 Audi Quattro Rally',
        'RampBuggy.truck': 'Ramp Buggy',
        'KickerRampV2.load': 'Kicker Ramp V2',
        '2014superduty.truck': '2014 Ford F-250 Super Duty XLT',
        '2014superduty-singlecab.truck': '2014 Ford F-250 Super Duty Single Cab',
        'BK84-BedTrailer.trailer': '1984 Toyota Longbed Trailer',
        'BK83Toyota.truck': '1983 Toyota Pickup Longbed 4x4',
        'BK84Toyota.truck': '1984 Toyota Pickup X-tra Cab Longbed',
        'BK84ToyotaSTD.truck': '1984 Toyota Pickup Single Cab Longbed',
        'BK84ToyotaSTD_C.truck': '1984 Toyota Pickup Single Cab Longbed Crawler',
        'BK84ToyotaSTD_IFS.truck': '1984 Toyota Pickup Single Cab Longbed IFS',
        'BK83ToyotaSnow.truck': '1983 Toyota Smari Sigurbjornsson Iceland Edition',
        'BK84ToyotaCustom.truck': '1984 Toyota Pickup Custom Cab Longbed',
        'BK84ToyotaSnow.truck': '1984 Toyota Custom Iceland Edition',
        'BK84ToyotaSnowTruck.truck': '1984 Toyota Custom Iceland truck',
        'BK83ToyotaSnowTruck.truck': '1983 Toyota Custom Iceland truck',
        'BK83ToyotaTrekker.truck': '1983 Toyota Trekker 4x4',
        'BK83ToyotaFlatbed.truck': '1983 Toyota Pickup Flatbed 4x4',
        'BK84ToyotaFlatbed.truck': '1984 Toyota Pickup Single Cab Flatbed',
        'BK84ToyotaCrawler.truck': '1984 Toyota Pickup Xtra cab Crawler',
        'BK83Toyota_Shortbed.truck': '1983 Toyota Pickup Shortbed 4x4',
        'BK84Toyota4R.truck': '1984 Toyota 4Runner',
        '73Chevy.truck': '1973 Chevy Single Cab Longbed',
        'BK85M1008.truck': '1985 M1008',
        'BK_73C10.truck': '1973 Chevy C10 Stepside',
        'BK_73_Suburban.truck': '1973 Chevy 2500 Suburban',
        'BK_85C10.truck': '1973 Chevy C10 Flareside',
        'BK_14x8.trailer': 'Carson 14x8ft Trailer',
        'BK67Patrol.truck': '1967 Nissan Patrol SWB',
        'BK67PatrolC.truck': '1967 Nissan Patrol LWB Crawler',
        'GMT400_scsb.truck': '1990 Chevy K1500 SCSB',
        'GMT400_trail.truck': '1998 Chevy Silverado K1500 Trail Truck',
        'BK86D21.truck': '1986 Nissan D21 4x4',
        'BK86D21Crawler.truck': '1986 Nissan D21 Crawler',
        'BK93Pathfinder.truck': '1993 Nissan Pathfinder 4x4',
        '51Chevy3100.truck': '1951 Chevy 3100 Street Rod',
        '1995C3500HD_bucket.truck': '1995 Chevy C3500HD Altec AT250G Bucket truck',
        'BBV954HU.truck': '1st Generation BlueBird Vision with Wheelchair Lift (Upgraded Lights)',
        '1990K3500_CREW_S.truck': '1990 Chevy k3500 Crew cab Single rear wheels',
        'BBV953U.truck': '1st Generation BlueBird Vision (Strobing) (Upgraded Lights)',
        'BBV952SM.truck': '1st Generation BlueBird Vision Short Bus (Mirrors)',
        'BBV952M.truck': '1st Generation BlueBird Vision (Non-Strobing) Mirrors',
        '1990K3500_Blazer_sas.truck': '1990 Chevy k2500 Blazer SAS',
        'BBV952S.truck': '1st Generation BlueBird Vision Short Bus',
        'BBV951M.truck': '1st Generation BlueBird Vision (Incandescent) Mirrors',
        '1990K3500_Suburban.truck': '1990 Chevy k2500 Suburban',
        '1990K3500_STD_LIFT.truck': '1990 Chevy k3500 Standard cab Single rear wheels (lift)',
        'BBV954M.truck': '1st Generation BlueBird Vision (G2 Fusion) Mirror',
        '1990K3500_EXT_C.truck': '1990 Chevy k3500 EXT cab Shortbed (custom)',
        '1990K3500_STD_S.truck': '1990 Chevy k3500 Standard cab Single rear wheels',
        'BBV95M.truck': '1st Generation BlueBird Vision (Mirrors)(0.38)',
        'BBV954HMU.truck': '1st Generation BlueBird Vision with Wheelchair Lift (Mirrors) (Upgraded Lights)',
        '1990K3500_CREW_D.truck': '1990 Chevy k3500 Crew Cab Dually',
        'BBV95S.truck': '1st Generation BlueBird Vision Short Bus (0.38)',
        '1990K3500_454.truck': '1990 Chevy 454ss',
        '1990K3500_EXT_D.truck': '1990 Chevy k3500 EXT Cab Dually',
        '1990K3500_STD_Sas.truck': '1990 Chevy k3500 Standard cab Single rear wheels sas',
        '1990K3500_STD_D.truck': '1990 Chevy k3500 Standard Cab Dually',
        'BBV953M.truck': '1st Generation BlueBird Vision (Strobing) Mirrors',
        'BBV954.truck': '1st Generation BlueBird Vision (G2 Fusion)',
        'BBV953MU.truck': '1st Generation BlueBird Vision (Strobing) (Mirrors) (Upgraded Lights)',
        'BBV954U.truck': '1st Generation BlueBird Vision (G2 Fusion) (Upgraded Lights)',
        '1990K3500_EXT_S.truck': '1990 Chevy k3500 EXT cab Single rear wheels',
        'BBV952SU.truck': '1st Generation BlueBird Vision Short Bus (Upgraded Lights)',
        'BBV952H.truck': '1st Generation BlueBird Vision with Wheelchair Lift',
        'BBV95H.truck': '1st Generation BlueBird Vision with Wheelchair Lift (0.38)',
        'BBV953.truck': '1st Generation BlueBird Vision (Strobing)',
        '1990K3500_Chassis.truck': '1990 Chevy K3500HD',
        '1990K3500_STD_C.truck': '1990 Chevy k3500 Standard cab (Modded)',
        'BBV952SMU.truck': '1st Generation BlueBird Vision Short Bus (Mirrors) (Upgraded Lights)',
        'BBV951.truck': '1st Generation BlueBird Vision (Incandescent)',
        'BBV95SM.truck': '1st Generation BlueBird Vision Short Bus (Mirrors)(0.38)',
        '1990K3500_454_S.truck': '1990 Chevy 454ss Stepside',
        'BBV954MU.truck': '1st Generation BlueBird Vision (G2 Fusion) (Mirrors) (Upgraded Lighting)',
        '1990K3500_STD_LOW.truck': '1990 Chevy 454ss (low)',
        'BBV952.truck': '1st Generation BlueBird Vision (Non-Strobing)',
        '1990K3500_Blazer.truck': '1990 Chevy k2500 Blazer',
        'BBV95.truck': '1st Generation BlueBird Vision (0.38)',
        'BBV952HM.truck': '1st Generation BlueBird Vision with Wheelchair Lift (Mirrors)',
        'BBV95HM.truck': '1st Generation BlueBird Vision with Wheelchair Lift (Mirrors)(0.38)',
        'Jason2013Vision.truck': 'Jason 2013 Bluebird Vision (6.7L ISB)',
        'Jason2017Vision.truck': 'Jason 2017 Bluebird Vision (6.7L ISB)',
        'Jason2018CE300.truck': 'Jason 2018 IC CE (Cummins 6.7L ISB)',
        'Jason2010CE300.truck': 'Jason 2010 IC CE300 (MaxxForce DT)',
        'Jason2009CE300.truck': 'Jason 2009 IC CE300 (MaxxForce DT)',
        'Jason2005CE200.truck': 'Jason 2005 IC CE200 (6.0L VT365)',
        'Jason2015CE300.truck': 'Jason 2015 IC CE (Cummins 6.7L ISB)',
        'Jason2012CE300.truck': 'Jason 2012 IC CE 300 (MaxxForce DT)',
        'Jason2006CE200.truck': 'Jason 2006 IC CE200 (6.0L VT365)',
        'Jason2013CE300.truck': 'Jason 2013 IC CE 300 (MaxxForce DT)',
        'Thomas_HDX-School.truck': 'Thomas Saf-T-Liner HDX (School)',
        'Thomas_HDX-Activity.truck': 'Thomas Saf-T-Liner HDX (Activity)',
        'Thomas_HDX-EMS.truck': 'Thomas Saf-T-Liner HDX (Emergency Medical Services)',
        'Thomas_HDX-School_fps.truck': 'Thomas Saf-T-Liner HDX (School) (FPS)',
        'Thomas_HDX-Activity_fps.truck': 'Thomas Saf-T-Liner HDX (Activity) (FPS)',
        'Thomas_HDX-EMS_fps.truck': 'Thomas Saf-T-Liner HDX (Emergency Medical Services) (FPS)',
        'Thomas_HDX-Transit.truck': 'Thomas Saf-T-Liner HDX (Transit)',
        'Thomas_HDX-Transit_fps.truck': 'Thomas Saf-T-Liner HDX (Transit) (FPS)',
        'Thomas_HDX-School-I.truck': 'Thomas Saf-T-Liner HDX (School) (Incandescent)',
        'Thomas_HDX-Activity_fps-I.truck': 'Thomas Saf-T-Liner HDX (Activity) (FPS) (Incandescent)',
        'Thomas_HDX-Activity-I.truck': 'Thomas Saf-T-Liner HDX (Activity) (Incandescent)',
        'Thomas_HDX-School_fps-I.truck': 'Thomas Saf-T-Liner HDX (School) (FPS) (Incandescent)',
        'Saf-T-LinerHDX1.truck': '2012 Saf-T-Liner HDX',
        'Saf-T-LinerHDX2.truck': '2012 Saf-T-Liner HDX (no mirrors)',
        'Saf-T-LinerHDX3.truck': '2012 Saf-T-Liner HDX (FPS)',
        'FLA95_semi.truck': 'Freightliner FLA Semi',
        '95_C2_LH.truck': 'Thomas Saf-T-Liner C2 (Handy)(LED)',
        '95_C2_LMH.truck': 'Thomas Saf-T-Liner C2 (Handy)(LED)(Mirrors)',
        '95_C2_LM.truck': 'Thomas Saf-T-Liner C2 (LED)(Mirrors)',
        '95_C2_IME.truck': 'Thomas Saf-T-Liner C2 (Side_E-Door)(Incandescent)(Mirrors)',
        '95_C2_LMS.truck': 'Thomas Saf-T-Liner C2 (Shorty)(LED)(Mirrors)',
        '95_C2_LMUE.truck': 'Thomas Saf-T-Liner C2 (Side_E-Door)(LED)(Mirrors)(Upgraded Stop Arm)',
        '95_C2_IM4.truck': 'Thomas Saf-T-Liner C2 (4X4)(Incandescent)(Mirrors)',
        '95_C2_IMS.truck': 'Thomas Saf-T-Liner C2 (Shorty)(Incandescent)(Mirrors)',
        '95_C2_I4.truck': 'Thomas Saf-T-Liner C2 (4X4)(Incandescent)',
        '95_C2_IMA.truck': 'Thomas Saf-T-Liner C2 (Activity Bus)(Incandescent)(Mirrors)',
        '95_C2_L.truck': 'Thomas Saf-T-Liner C2 (LED)',
        '95_C2_IA.truck': 'Thomas Saf-T-Liner C2 (Activity Bus)(Incandescent)',
        '95_C2_I.truck': 'Thomas Saf-T-Liner C2 (Incandescent)',
        '95_C2_LME.truck': 'Thomas Saf-T-Liner C2 (Side_E-Door)(LED)(Mirrors)',
        '95_C2_IS.truck': 'Thomas Saf-T-Liner C2 (Shorty)(Incandescent)',
        '95_C2_LUE.truck': 'Thomas Saf-T-Liner C2 (Side_E-Door)(LED)(Upgraded Stop Arm)',
        '95_C2_IMH.truck': 'Thomas Saf-T-Liner C2 (Handy)(Incandescent)(Mirrors)',
        '95_C2_LMU.truck': 'Thomas Saf-T-Liner C2 (LED)(Mirrors)(Upgraded Stop Arm)',
        '95_C2_LMUH.truck': 'Thomas Saf-T-Liner C2 (Handy)(LED)(Mirrors)(Upgraded Stop Arm)',
        '95_C2_IH.truck': 'Thomas Saf-T-Liner C2 (Handy)(Incandescent)',
        '95_C2_LMUS.truck': 'Thomas Saf-T-Liner C2 (Shorty)(LED)(Mirrors)(Upgraded Stop Arm)',
        '95_C2_LE.truck': 'Thomas Saf-T-Liner C2 (Side_E-Door)(LED)',
        '95_C2_LU.truck': 'Thomas Saf-T-Liner C2 (LED)(Upgraded Stop Arm)',
        '95_C2_IE.truck': 'Thomas Saf-T-Liner C2 (Side_E-Door)(Incandescent)',
        '95_C2_LUS.truck': 'Thomas Saf-T-Liner C2 (Shorty)(LED)(Upgraded Stop Arm)',
        '95_C2_LS.truck': 'Thomas Saf-T-Liner C2 (Shorty)(LED)',
        '95_C2_IM.truck': 'Thomas Saf-T-Liner C2 (Incandescent)(Mirrors)',
        '95_C2_LUH.truck': 'Thomas Saf-T-Liner C2 (Handy)(LED)(Upgraded Stop Arm)',
        'f150shortbed79.truck': 'Ford F-150 Short Bed (1979)',
        'f250_84_extcab_cap.truck': 'Ford F-250 Custom Extended Cab W/ Bed Cap (1984)',
        'f250_99_extcab.truck': 'Ford F-250 SuperDuty Supercab (1999)',
        'f350_84_regcab.truck': 'Ford F-350 Custom Regular Cab W/ Dana 60 Axle (1984)',
        'bronco_84.truck': 'Ford Bronco (1984)',
        'bronco_84_nocap.truck': 'Ford Bronco W/ No Cap (1984)',
        'f350crewcab79.truck': 'Ford F-350 Crew Cab (1979)',
        'f150_84_shortbed.truck': 'Ford F-150 Custom Short Bed (1984)',
        'f100_76_longbed.truck': 'Ford F-100 Custom Long Bed (1976)',
        'f150_92_longbed.truck': 'Ford F-150 XL Long Bed (1992)',
        'broncocen79.truck': 'Ford Bronco Centurion (1979)',
        'bronco_84_nospare.truck': 'Ford Bronco W/ No Spare Tire (1984)',
        'f150_84_stepside.truck': 'Ford F-150 Custom Stepside Bed (1984)',
        'f150_76_explorer.truck': 'Ford F-150 Custom Explorer (1976)',
        'f100_76_stepside.truck': 'Ford F-100 Custom Stepside Bed (1976)',
        'f350_84_crewdually.truck': 'Ford F-350 Custom Crew Cab Dually W/ Dana 60 Axle (1984)',
        'f150_84_extcab.truck': 'Ford F-150 Custom Extended Cab (1984)',
        'f150_92_extcab.truck': 'Ford F-150 XL Extended Cab (1992)',
        'f150bigfoot1.truck': 'Ford F-250 "Bigfoot" (1976)',
        'f250clubcab79.truck': 'Ford F-250 Club Cab (1979)',
        'f150_92_shortbed.truck': 'Ford F-150 XL Short Bed (1992)',
        'f150_84_longbed.truck': 'Ford F-150 Custom Long Bed (1984)',
        'f350_84_crewcab.truck': 'Ford F-350 Custom Crew Cab W/ Dana 60 Axle (1984)',
        'f150_84_explorer.truck': 'Ford F-150 Explorer Short Bed (1984)',
        'bronco79.truck': 'Ford Bronco (1979)',
        'f250_84_regcab_cap.truck': 'Ford F-250 Custom Long Bed w/ Bed Cap (1984)',
        'f150shortbed75.truck': 'Ford F-150 Short Bed (1976)',
        'f600_86_singlecab_flatbed.truck': 'Ford F-600 Single Cab Flatbed',
        'f150_92_nite_longbed.truck': 'Ford F-150 Nite Long Bed (1992)',
        'f150explorer75.truck': 'Ford F-150 Explorer (1976)',
        'f250clubcab75.truck': 'Ford F-250 Club Cab (1976)',
        'f350_84_regdually.truck': 'Ford F-350 Custom Regular Cab Dually W/ Dana 60 Axle (1984)',
        'f150longbed75.truck': 'Ford F-150 Long Bed (1976)',
        'f100_76_shortbed.truck': 'Ford F-100 Custom Short Bed (1976)',
        'f150_84_longbedcap.truck': 'Ford F-150 Custom Long Bed w/ Bed Cap (1984)',
        'f150_92_svt.truck': 'Ford F-150 SVT Lightning (1992)',
        'f150_87_longbed.truck': 'Ford F-150 Long Bed (1987)',
        'f350crewcab75.truck': 'Ford F-350 Crew Cab (1976)',
        'bronco_92.truck': 'Ford Bronco (1992)',
        'f150_76_stepside.truck': 'Ford F-150 Custom Stepside Bed (1976)',
        'f100_76_gasser.truck': 'Ford F-100 "The Butthurt Express" (1976)',
        'f150_76_shortbed.truck': 'Ford F-150 Custom Short Bed (1976)',
        'f100_67_longbed.truck': 'Ford F-100 Custom Long Bed (1967)',
        'f150_76_longbed.truck': 'Ford F-150 Custom Long Bed (1976)',
        'f250_84_regcab.truck': 'Ford F-250 Custom Regular Cab (1984)',
        'f150_76_supercab.truck': 'Ford F-150 Custom Supercab (1976)',
        'f250_84_extcab.truck': 'Ford F-250 Custom Extended Cab (1984)',
        'f350_67_crewcab.truck': 'Ford F-350 Custom Crew Cab (1967)',
        'f150longbed79.truck': 'Ford F-150 Long Bed (1979)',
        'vh-1800.truck': 'Thomas S1800',
        'vh-3800.truck': 'Thomas 3800',
        'vh-fs65.truck': 'Thomas FS-65',
        'vh-monsterbus.truck': 'Thomas 4x4 Monster Bus'
}
